### ISSUE TITLE
108 | Convert Sorted Array to Binary Search Tree | C++

### ISSUE THREAD

**Issue by harshbhagwani94** [SHY-Corp/LeetCode-Solutions#1004]
## **`Title`** - Convert Sorted Array to Binary Search Tree

**What will change** - A solution file will be added.

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by harshbhagwani94** [comment]
Can someone assign this issue to me?

**Comment by AmeyaPhadnis-2019H1030012G** [comment]
Please assign this issue to me. I am new to the open-source community and looking forward to opportunities to contribute. Thanks in advance!
