### ISSUE TITLE
14 | Longest Common Prefix | Java

### ISSUE THREAD

**Issue by Vrindagupta6828** [SHY-Corp/LeetCode-Solutions#101]
## **`Title`** -  Write a function to find the longest common prefix string amongst an array of strings.

If there is no common prefix, return an empty string "".

**What will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Java

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by Vrindagupta6828** [comment]
I want to work on this.

**Comment by chiillax** [comment]
I am interested to contribute.

**Comment by Vrindagupta6828** [comment]
@chiillax please create your own issue

**Comment by princekalra** [comment]
want to contribute

**Comment by SSKale1** [comment]
- [x] Assigned to @Vrindagupta6828 for issue creation

**Comment by Pranit5895** [comment]
want to contribute

**Comment by Aditya489** [comment]
i want to contribute in it!

**Comment by psymbio** [comment]
I want to contribute solution 905 and 977 in Java.
