### ISSUE TITLE
198 | House Robber | CPP

### ISSUE THREAD

**Issue by pstreemaze** [SHY-Corp/LeetCode-Solutions#1016]
## House Robber

**What will change** -
 Add a well documented and optimum code
### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by chiillax** [comment]
I want to work on it.

**Comment by Starkultra** [comment]
I already solved this one could please assign this issue..

**Comment by pstreemaze** [comment]
Waiting for it to be assigned to me, I solved it already too

**Comment by pstreemaze** [comment]
Why unassigned?
