### ISSUE TITLE
101 | Symmetric Tree | CPP

### ISSUE THREAD

**Issue by pstreemaze** [SHY-Corp/LeetCode-Solutions#1017]
## Symmetric tree
Add a code

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by chiillax** [comment]
Could you please assign me for this task ?

**Comment by Starkultra** [comment]
Please assign this issue to me..

**Comment by pstreemaze** [comment]
Why unassigned
