### ISSUE TITLE
994 | Rotting Oranges | Cpp | Python | Java

### ISSUE THREAD

**Issue by chiillax** [SHY-Corp/LeetCode-Solutions#102]
## In a given grid, each cell can have one of three values:

the value 0 representing an empty cell;
the value 1 representing a fresh orange;
the value 2 representing a rotten orange.
Every minute, any fresh orange that is adjacent (4-directionally) to a rotten orange becomes rotten.

Return the minimum number of minutes that must elapse until no cell has a fresh orange.  If this is impossible, return -1 instead.

**What will change** -

### Type of Issue -

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python
- [x] C++
- [x] Java
- [x] SQL

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Happy Coding,

**Comment by chiillax** [comment]
I want to work on it.

**Comment by chiillax** [comment]
Please checkout #108

**Comment by SSKale1** [comment]
Please create a single issue per language and code. Also go through the Contribution guidelines and follow the required formats.
