### ISSUE TITLE
746 | Min Cost Climbing Stairs | C++

### ISSUE THREAD

**Issue by alpha-k911** [SHY-Corp/LeetCode-Solutions#1031]
## **`Title`** - 746. Min Cost Climbing Stairs

**What will change** - Adding 746. Min Cost Climbing Stairs (https://leetcode.com/problems/min-cost-climbing-stairs/)

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by alpha-k911** [comment]
Please assign me to this issue @swaingotnochill  @SSKale1 @JOKUE2002

**Comment by JOKUE2002** [comment]
Here you go.

**Comment by alpha-k911** [comment]
Hey thanks @JOKUE2002

**Comment by alpha-k911** [comment]
I want to be part of this team. Can you please look into it? You can check my Github profile whether to consider me or not. @JOKUE2002 @swaingotnochill @SSKale1
