### ISSUE TITLE
45 | Jump Game II | CPP

### ISSUE THREAD

**Issue by pstreemaze** [SHY-Corp/LeetCode-Solutions#1032]
## **`Title`** - Jump Game II

**What will change** -

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by AhmadShaaban** [comment]
can I work on this?

**Comment by ArshdeepSingh98** [comment]
Hi, I want to work on this issue.

**Comment by SSKale1** [comment]
An open issue for this problem already exists.

**Comment by ArshdeepSingh98** [comment]
Ok 👍
