### ISSUE TITLE
322 | Coin Change | CPP

### ISSUE THREAD

**Issue by pstreemaze** [SHY-Corp/LeetCode-Solutions#1033]
## **`Title`** - Coin Change

**What will change** -

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by haxpor** [comment]
Hi there @pstreemaze , I'd like to work on this, please assign it to me. Thanks!

**Comment by AhmadShaaban** [comment]
can I work on this?

**Comment by haxpor** [comment]
If you check the code base, there is already 322 solution there. So either someone get passed the contribution process, or mis-communication there.

**Comment by SSKale1** [comment]
Problem already exists in the codebase.
