### ISSUE TITLE
940 | Distinct Subsequence II | C++

### ISSUE THREAD

**Issue by idivyamgoyal** [SHY-Corp/LeetCode-Solutions#1041]
## **`Distinct Subsequence II`** -

**What will change** - Adding new code

### Type of Issue - Soln for the problem

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by ArshdeepSingh98** [comment]
Hi, can you assign this to me?

**Comment by idivyamgoyal** [comment]
> Hi, can you assign this to me?

Hi, sorry but I opened this issue for myself.

**Comment by ArshdeepSingh98** [comment]
Ok, no problem
