### ISSUE TITLE
1351 | Count Negative Numbers in a Sorted Matrix | CPP

### ISSUE THREAD

**Issue by ArshdeepSingh98** [SHY-Corp/LeetCode-Solutions#1044]
## **`Count Negative Numbers in a Sorted Matrix`** -

**What will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by aminasadiam** [comment]
hi @ArshdeepSingh98, May I work on this?

**Comment by ArshdeepSingh98** [comment]
Sorry, I have assigned this myself. You can create a new issue.

**Comment by aminasadiam** [comment]
No problem, good luck. 👍
