### ISSUE TITLE
633 | Sum of Square Numbers | C++

### ISSUE THREAD

**Issue by Darsh4521** [SHY-Corp/LeetCode-Solutions#1049]
## **`Sum of Square Numbers`** -

**What will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [] Improving Code
- [] Improving Documentation
- [] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [] Python
- [x] C++
- [] Java
- [] SQL

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by Darsh4521** [comment]
Assign this to me please

**Comment by Mrinal-Choudhary07** [comment]
assign this to me ,Iam ready.

**Comment by tanishaPandey-2019** [comment]
Please assign this issue to me

**Comment by shinchancode** [comment]
please assign this to me

**Comment by Shreyas-Gupta-21** [comment]
Hello I'm Interested to work on this. Pls assign this to me

**Comment by Darsh4521** [comment]
@SSKale1 check the pull request I have mentioned here the issue was raised 5 days ago still the pull request is not merged
