### ISSUE TITLE
1234 | Divide two numbers using only subtraction (-) operator | Python

### ISSUE THREAD

**Issue by aminasadiam** [SHY-Corp/LeetCode-Solutions#1051]
## **`Divide two numbers using only subtraction (-) operator`** -

**What will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by aminasadiam** [comment]
Assign this to me please

**Comment by tyagi619** [comment]
Please assign this to me

**Comment by aminasadiam** [comment]
Dear @tyagi619 , Sorry, I have assigned this to myself.
