### ISSUE TITLE
59. | Spiral Matrix Part-II | C++

### ISSUE THREAD

**Issue by vishalghosh7** [SHY-Corp/LeetCode-Solutions#1058]
## **Title** - Spiral Matrix II

**What will change** - Addition of an efficient code for the 2nd type of LeetCode Spiral Matrix problem

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.
- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by SSKale1** [comment]
Duplicate issue #688 already exists.
