### ISSUE TITLE
13 | Roman To Integer | Java

### ISSUE THREAD

**Issue by Kingal1337** [SHY-Corp/LeetCode-Solutions#106]
## **`Roman To Integer`** -
This program will convert a roman numeral into an integer
**What will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Java

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by guygreenleaf** [comment]
Hi there, 

I can do this in C++ , feel free to assign me :)

**Comment by SSKale1** [comment]
@guygreenleaf you can create another issue for the same and we'll assign it to you.

**Comment by taneemishere** [comment]
I can do this... Let this assign to me.

**Comment by Hutcheeran** [comment]
Hiya! Can you assign this to me?
