### ISSUE TITLE
1119 | Remove Vowels from a String | Python

### ISSUE THREAD

**Issue by ngutierrez31** [SHY-Corp/LeetCode-Solutions#1061]
## **`Remove Vowels from a String `** -

**What will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
-  x Improving Code
-  x Improving Documentation
-  x Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [x] Python
-  x C++
-  x  Java
-  x SQL

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by ngutierrez31** [comment]
I'd like to be assigned to this please

**Comment by gurleendhod** [comment]
Could you please assign this to me?

**Comment by Priyanshu1012** [comment]
Could you please assign this issue to me ?

**Comment by sowmya8900** [comment]
Could you please assign this issue to me?
- Sowmya
