### ISSUE TITLE
1463 | Cherry Pickup II | C++

### ISSUE THREAD

**Issue by kross9924** [SHY-Corp/LeetCode-Solutions#1063]
## **`Title`** -  Cherry Pickup II

**What will change** -  Solution for above problem will be added

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by kross9924** [comment]
.

**Comment by AbhJ** [comment]
Please assign to me I am a third year undergraduate in Electrical Engineering IIT Kharagpur with good background in competitive programming
