### ISSUE TITLE
Invalid

### ISSUE THREAD

**Issue by Starkultra** [SHY-Corp/LeetCode-Solutions#1078]
## **`Title`** -  3Sum-Closet 
 
**What will change** - New problem will be added to the folder C++

### Type of Issue -

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by Starkultra** [comment]
please assign this issue

**Comment by AbhJ** [comment]
Please assign to me I am a third year undergraduate in Electrical Engineering IIT Kharagpur with good background in competitive programming

**Comment by swaingotnochill** [comment]
@ABhJ open the leedcode solutions repository and search for problems that are missing in repo and create a  issue concerning missing solutions. I will assign you that..
