### ISSUE TITLE
11228 | Divide two numbers using only subtraction (-) operator | Python

### ISSUE THREAD

**Issue by aminasadiam** [SHY-Corp/LeetCode-Solutions#1085]
## **`Divide two numbers using only subtraction (-) operator`** - 11228

**What will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by chiillax** [comment]
Could you please assign me for this task ?

**Comment by aminasadiam** [comment]
May I work on this?

**Comment by AbhJ** [comment]
Please assign to me I am a third year undergraduate in Electrical Engineering IIT Kharagpur with good background in competitive programming

**Comment by Dbhasin1** [comment]
May I work on this?
