### ISSUE TITLE
1626 | Best Team With No Conflicts | C++

### ISSUE THREAD

**Issue by Mannan2812** [SHY-Corp/LeetCode-Solutions#1092]
## **`Best Team With No Conflicts`** -

**New File in c++ directory** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by Mannan2812** [comment]
Please assign this issue to me.

**Comment by Mannan2812** [comment]
@Yashica7 @SSKale1

**Comment by AbhJ** [comment]
Please assign to me I am a third year undergraduate in Electrical Engineering IIT Kharagpur with good background in competitive programming
