### ISSUE TITLE
83 | Remove Duplicates from Sorted List | C++

### ISSUE THREAD

**Issue by jaisai6** [SHY-Corp/LeetCode-Solutions#1093]
## **`Title`** - Remove Duplicates from Sorted List
**What will change** -
Solution will be added to the repo

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by jaisai6** [comment]
Please assign this to me

**Comment by AbhJ** [comment]
Please assign to me I am a third year undergraduate in Electrical Engineering IIT Kharagpur with good background in competitive programming

**Comment by jaisai6** [comment]
Actually, I have solved that problem. So, I am just waiting for them to
assign it to me.

**Comment by AbhJ** [comment]
so have i

**Comment by shinchancode** [comment]
can u please assign this to me. this is my first hactoberfest request.

**Comment by 0ChanAk** [comment]
please assign this issue to me, I want to work on this.

**Comment by Shreyas-Gupta-21** [comment]
Hello I'm Interested to work on this. Pls assign this to me
