### ISSUE TITLE
454 | 4 Sum II | JAVA

### ISSUE THREAD

**Issue by JOKUE2002** [SHY-Corp/LeetCode-Solutions#11]
## **`Medium rated challenge no. 454`**

**What will change**

The solution to the challenge no. 454 will be added, which requires the code to find all the specific tuples in a set of four one dimensional arrays.

### Type of Issue

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

- [ ] Python
- [ ] C++
- [x] Java

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/Ftbj4a

Happy Coding,
JOKUE2002

**Comment by JOKUE2002** [comment]
I would love to claim this one myself 😅

**Comment by Yashica7** [comment]
Assigning to @JOKUE2002
