### ISSUE TITLE
997 | Find the Town Judge | C++

### ISSUE THREAD

**Issue by jaisai6** [SHY-Corp/LeetCode-Solutions#1116]
## **`Title`** - Find the Town Judge

**What will change** - solution will be added to the repo

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by jaisai6** [comment]
Please assign this issue

**Comment by NancyAgrawal** [comment]
Hey, I'll like to work on this.
