### ISSUE TITLE
504 | Base 7 | CPP

### ISSUE THREAD

**Issue by pstreemaze** [SHY-Corp/LeetCode-Solutions#1120]
## **`Title`** -
BASE 7
**What will change** -

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by jaisai6** [comment]
Please assign this issue to me..
