### ISSUE TITLE
383 | Ransom Note | CPP

### ISSUE THREAD

**Issue by pstreemaze** [SHY-Corp/LeetCode-Solutions#1122]
## **`Title`** -
RANSOM NOTE
**What will change** -

### Type of Issue -

.

- [x] Adding New Code

### Programming Language

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by rematchka** [comment]
Please assign this issue to me.

**Comment by charles-vj** [comment]
Interested in contributing . Kindly assign this issue to me

**Comment by JOKUE2002** [comment]
@pstreemaze I assigned you to #1120 

I'll assign this to @rematchka for now.

@charles-vj you may select other issues you want to work on.

**Comment by pstreemaze** [comment]
> @pstreemaze I assigned you to #1120
> 
> I'll assign this to @rematchka for now.
> 
> @charles-vj you may select other issues you want to work on.

I wanted all three issues for hacktoberfest, but nevermind
