### ISSUE TITLE
176 | Second Highest Salary | SQL

### ISSUE THREAD

**Issue by pstreemaze** [SHY-Corp/LeetCode-Solutions#1124]
## **`Title`** -
Second Highest Salary
**What will change** -

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] SQL

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by SudhiMohan** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by JOKUE2002** [comment]
@pstreemaze I assigned you a different issue. I'll hand this to @SudhiMohan for now.

**Comment by SudhiMohan** [comment]
Hi  @JOKUE2002  , Thanks for assigning the issue to me. I have created a pull request #1198  with the solution. Please check it out when you get time. 

Also thanks @pstreemaze for creating the issue.

**Comment by NikhilTaneja98** [comment]
Please assign me this issue?
