### ISSUE TITLE
1313 | Title-Decompress Run-Length Encoded List | C++

### ISSUE THREAD

**Issue by himanshu81023** [SHY-Corp/LeetCode-Solutions#1125]
## **`Title`** -Decompress Run-Length Encoded  (NEW SOLUTION WILL BE ADDED)
**What will change** -
    New solution

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Code

### Programming Language

Please add/delete options that are not relevant.
- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**PLEASE ASSIGN THIS TO ME**

**Comment by himanshu81023** [comment]
ASSIGN THIS TO ME

**Comment by Dimplesinha** [comment]
Assign this to me

**Comment by JOKUE2002** [comment]
@himanshu81023 the code for solution 1313 is already submitted in C++ 

I'll close this for now. You may create more issues.
