### ISSUE TITLE
148 | Sort List | Python

### ISSUE THREAD

**Issue by hardikchoudhary12** [SHY-Corp/LeetCode-Solutions#1127]
## **`Title`** -

Python solution for 148 Sort List

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Code
- [x] Improving Documentation
- [x] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [x] Python
- [ ] C++
- [ ] Java
- [ ] SQL

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by hardikchoudhary12** [comment]
Can this issue be assigned to me?

**Comment by gustavomv** [comment]
can I have this one? plss

**Comment by Shreyas-Gupta-21** [comment]
Hello I'm Interested to work on this. Pls assign this to me
