### ISSUE TITLE
137 | Single Number II | Python

### ISSUE THREAD

**Issue by JayeshSareen** [SHY-Corp/LeetCode-Solutions#114]
Single Number II

**What will change** -

### Type of Issue -

-  Adding New Code

### Programming Language

-  Python

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by Nithin005** [comment]
plz assign it to me

**Comment by JayeshSareen** [comment]
Actually I want to do this. Please let me work on this

**Comment by SSKale1** [comment]
- [x] Assigning to @JayeshSareen for issue creation

**Comment by Nithin005** [comment]
bruh i asked first. orelse he must have mentioned that he is doing this during issue creation.

**Comment by SSKale1** [comment]
@Nithin005 The first preference will be given to the issue creator, always.

**Comment by OMEGAeNcore** [comment]
Can I be assigned to this?

**Comment by adhamale2810** [comment]
Please assign it to me. I will give my best for the contribution.
Thank You.

**Comment by SSKale1** [comment]
@adhamale2810 you can create your own issue.
