### ISSUE TITLE
852 | Peak Index in a Mountain Array | C++

### ISSUE THREAD

**Issue by NancyAgrawal** [SHY-Corp/LeetCode-Solutions#1149]
## **`Title`** - Peak Index in a Mountain Array

**What will change** - Add solution for the problem `852. Peak Index in a Mountain Array` in C++

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by NancyAgrawal** [comment]
Can you assign it to me, please?

**Comment by Ansh8236** [comment]
Hey! I would like to work on this problem.
