### ISSUE TITLE
287 |  Python / FindTheDuplicateNumber.py | Python

### ISSUE THREAD

**Issue by himanshu81023** [SHY-Corp/LeetCode-Solutions#1155]
## **`FindTheDuplicateNumber`** -

**What will change** -
     Will make code more efficient.
     Currently time complexity of soln. is (n^2), after changes it will of 0(n*log(n))

### Type of Issue -

- [x] Adding New Code
- [x] Improving Code

### Programming Language

- [x] Python

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

**_Please assign this to  me_**

Happy Coding,

**Comment by himanshu81023** [comment]
**_Consider me  for this_**

**Comment by adrputra** [comment]
I'll do it, assign me

**Comment by sowmya8900** [comment]
Could you please assign this issue to me?

**Comment by vincentsuryakim** [comment]
Please assign this issue to ne

**Comment by Shreyas-Gupta-21** [comment]
Hello I'm Interested to work on this. Pls assign this to me

**Comment by iMPERIAL18** [comment]
Please assign me to this.
