### ISSUE TITLE
925 | Long Pressed Name | c++

### ISSUE THREAD

**Issue by naveen81** [SHY-Corp/LeetCode-Solutions#1157]
## **`Title`** - Long Pressed Name

**What will change** - Add solution for this problem

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language
c++
Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by jaisai6** [comment]
Please assign this to me.
