### ISSUE TITLE
5 | Longest Palindromic Substring | Python

### ISSUE THREAD

**Issue by akash02ab** [SHY-Corp/LeetCode-Solutions#116]
## **`Title`** - Longest Palindromic Substring

**What will change** -  LeetCode-Solutions/Python/

### Type of Issue 

- [x] Adding New Code

### Programming Language

- [x] Python

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by hjpassion** [comment]
please assign it to me i want to add some solution to this program

**Comment by Aditya489** [comment]
i want to contribute in it!

**Comment by SSKale1** [comment]
- [x] Assigned to @akash02ab for issue creation

**Comment by OMEGAeNcore** [comment]
please can you assign this to me?

**Comment by prikshitsetia** [comment]
Hey, I would like to contribute to this
