### ISSUE TITLE
Number of Distinct Islands

### ISSUE THREAD

**Issue by pallavi267** [SHY-Corp/LeetCode-Solutions#1160]
Given a non-empty 2D arraygridof 0's and 1's, an island is a group of1's (representing land) connected 4-directionally (horizontal or vertical.) You may assume all four edges of the grid are surrounded by water.
Count the number of distinct islands. An island is considered to be the same as another if and only if one island can be translated (and not rotated or reflected) to equal the other.

**Comment by pallavi-bits** [comment]
Please assign the issue to me.
