### ISSUE TITLE
18. | 4Sum | C++

### ISSUE THREAD

**Issue by vishalghosh7** [SHY-Corp/LeetCode-Solutions#1162]
## **`Title`** - 4Sum

**What will change** - Adding a solution code in C++ for the mentioned problem.

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by vishalghosh7** [comment]
Would you please assign this issue to me?

**Comment by Shreyas-Gupta-21** [comment]
Hello I'm Interested to work on this. Pls assign this to me
