### ISSUE TITLE
347 | Top K Frequent Elements | Python

### ISSUE THREAD

**Issue by javmarina** [SHY-Corp/LeetCode-Solutions#1171]
## **`Top K Frequent Elements`**

https://leetcode.com/problems/top-k-frequent-elements/

**What will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by javmarina** [comment]
I'm ready, pleasi assign this to me

**Comment by Aarav545** [comment]
@swaingotnochill @JOKUE2002 @SSKale1 Can you please assign this to me?

**Comment by javmarina** [comment]
Thanks!
