### ISSUE TITLE
983 | Minimum Cost For Tickets | Java

### ISSUE THREAD

**Issue by shvms** [SHY-Corp/LeetCode-Solutions#1172]
## **`Title`** - Minimum Cost For Tickets

**What will change** - Add solution for `983. Minimum Cost For Tickets`

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Java

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by shvms** [comment]
Please assign this issue to me @SSKale1 @swaingotnochill @Yashica7

**Comment by JOKUE2002** [comment]
@shvms please select only one language

**Comment by shvms** [comment]
@JOKUE2002 I've edited the issue.
