### ISSUE TITLE
785 | Is graph bipartite | Python

### ISSUE THREAD

**Issue by pbharathreddy** [SHY-Corp/LeetCode-Solutions#1177]
## **`Is graph Bipartite** -

**What will change** -

Will add a new file called '785. IsGraphBipartite'.

### Type of Issue -

Code commit.

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by Azanul** [comment]
Asking for assignment.

**Comment by pbharathreddy** [comment]
Created this issue because I would like to work on it.

**Comment by Alifbhanvadiya14** [comment]
I want to work in python
Plz Assign to me
