### ISSUE TITLE
25 | Reverse Nodes in k-Group | Python

### ISSUE THREAD

**Issue by Azanul** [SHY-Corp/LeetCode-Solutions#1182]
## **`Reverse Nodes in k-Group`** -

**What will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by Azanul** [comment]
Asking for assignment

**Comment by pallavi-bits** [comment]
hey do u have any idea how long it takes for major contributors to reply or assign the task?

**Comment by Azanul** [comment]
No, I don't but if you are trying to complete hacktoberfest then you can create PRs in various repos, that way you can get atleast 4 of them merged.
