### ISSUE TITLE
33 | Search in Rotated Sorted Array | C++

### ISSUE THREAD

**Issue by Aaryan2104** [SHY-Corp/LeetCode-Solutions#1186]
## **33. Search in Rotated Sorted Array** -

**What will change** - Adding code (problem unsolved in repo)

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by syn2k** [comment]
Please assign to me

**Comment by Shreyas-Gupta-21** [comment]
Hello I'm Interested to work on this. Pls assign this to me

**Comment by ishikalohia** [comment]
Please assign this issue to me.

**Comment by sourabhjain9887** [comment]
please assign this issue to me.

**Comment by SSKale1** [comment]
Duplicate of Issue #700
