### ISSUE TITLE
203 | Remove Linked List Elements | C++

### ISSUE THREAD

**Issue by JasirZaeem** [SHY-Corp/LeetCode-Solutions#119]
## **`Remove Linked List Elements`** -

**What will change** - Add solution

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by JasirZaeem** [comment]
I would like to be assigned this.

**Comment by H4D3N** [comment]
Can i be assigned for this. i would like to solve this problem in c++ with a proper documentation

**Comment by hjpassion** [comment]
if there is any task left here then please give me an opportunity to try

**Comment by SSKale1** [comment]
@hjpassion there are a about 1600 problems on https://leetcode.com/problemset/all/ you can take up any one and create an issue for it following the proper format according to the contribution guidelines.

**Comment by SSKale1** [comment]
- [x] Assigning to @JasirZaeem for issue creation

**Comment by SSKale1** [comment]
@H4D3N you can select any LC problem and create an issue for the same.
