### ISSUE TITLE
601 | Human Traffic of Stadium | C++

### ISSUE THREAD

**Issue by 0ChanAk** [SHY-Corp/LeetCode-Solutions#1196]
## **`Title: 601. Human Traffic of Stadium`** 

**What will change: add a solution to this problem in SQL** 

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] SQL

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,
@JOKUE2002 please assign this issue to me. thanks.

**Comment by jvishad** [comment]
please assign this issue to me. thanks in advance.:)
