### ISSUE TITLE
180 | Consecutive Numbers | SQL

### ISSUE THREAD

**Issue by saintpopo** [SHY-Corp/LeetCode-Solutions#1201]
## **`Title`** - Consecutive Numbers

**What will change** - Adding 108.Consecutive Numbers
(https://leetcode.com/problems/consecutive-numbers/)

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] SQL

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by saintpopo** [comment]
@JOKUE2002  please assign it to me.

**Comment by jvishad** [comment]
please assign it to me.
