### ISSUE TITLE
12. | Integer to Roman | Python

### ISSUE THREAD

**Issue by kajal-puri** [SHY-Corp/LeetCode-Solutions#1208]
## **`12. Integer to Roman in Python`** -

**What will change** - Adding code for the Problem 12. Integer to Roman in Python.

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by kajal-puri** [comment]
@SSKale1 Hi, Can you please assign this to me?

**Comment by Hrithik1211** [comment]
Can you please assign this to me ? Thanks in advance

**Comment by ghanender-chauhan** [comment]
assign this to me

**Comment by ghanender-chauhan** [comment]
i will do in python

**Comment by ghanender-chauhan** [comment]
@swaingotnochill  accept my PR i did in python !!
