### ISSUE TITLE
19 | Remove Nth Node From End of List | Python

### ISSUE THREAD

**Issue by kajal-puri** [SHY-Corp/LeetCode-Solutions#1209]
## **`19. Remove Nth Node From End of List in Python`**

**What will change** - Adding new code of Problem 19 in Python

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding.

**Comment by kajal-puri** [comment]
Hi, can this be please assigned to me?

**Comment by Shreyas-Gupta-21** [comment]
Hello I'm Interested to work on this. Pls assign this to me

**Comment by namrata18s** [comment]
Please assign it to me

**Comment by Alifbhanvadiya14** [comment]
please assign to me
