### ISSUE TITLE
21 | Merge Two Sorted Lists | Python

### ISSUE THREAD

**Issue by kajal-puri** [SHY-Corp/LeetCode-Solutions#1210]
## **`Title`** - 21. Merge Two Sorted Lists in Python

**What will change** - Adding New code in Python

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by kajal-puri** [comment]
Can you assign this to me? Thanks.

**Comment by Hrithik1211** [comment]
Can you please assign this to me ? Thanks

**Comment by naresh2002** [comment]
I am new to github but decent enough to do this task. So can you please assign it to me?

**Comment by Shreya-art** [comment]
can you assign it to me?

**Comment by Shreyas-Gupta-21** [comment]
Hello I'm Interested to work on this. Pls assign this to me

**Comment by namrata18s** [comment]
Can you assign me?

**Comment by pragat-pandya** [comment]
I would like to work on this task .
