### ISSUE TITLE
6 ZigZag Conversion Cpp

### ISSUE THREAD

**Issue by jvishad** [SHY-Corp/LeetCode-Solutions#1222]
ZigZag Conversion

**What will change** - I am adding code for this problem.

### Type of Issue - Adding code which i had written on leetcode and submitted.

Please add/delete options that are not relevant.

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language 

Please add/delete options that are not relevant.

- [ ] Python
- [x] C++
- [ ] Java
- [ ] SQL

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by jvishad** [comment]
Please assign this task.:)

**Comment by SSKale1** [comment]
This problem already exists in the codebase.
