### ISSUE TITLE
12| Buddy Strings | Java

### ISSUE THREAD

**Issue by Vasvisood** [SHY-Corp/LeetCode-Solutions#1223]
### Adding a solution

- [x] Adding New Code
- [x] Improving Code
- [x] Improving Documentation
- [x] Bug Fix

### Java

Please add/delete options that are not relevant.

- [x] Python
- [x] C++
- [x] Java
- [x] SQL

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by yourdad285** [comment]
how to solve it ?? Assign to me.

**Comment by verma-shivani** [comment]
please assign this to me
