### ISSUE TITLE
714 | Best Time to Buy and Sell Stock with Transaction Fee | c++

### ISSUE THREAD

**Issue by prakharpande** [SHY-Corp/LeetCode-Solutions#1226]
## **`Title`** - Best Time to Buy and Sell Stock with Transaction Fee

**What will change** - Adding Code for problem no 714

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by prakharpande** [comment]
please assign this issue to me.

**Comment by sourabhjain9887** [comment]
please assign this issue to me .
