### ISSUE TITLE
23| Merge k Sorted Lists | java

### ISSUE THREAD

**Issue by muskan-sudo** [SHY-Corp/LeetCode-Solutions#1232]
## **`Title`** - Merge k Sorted Lists

**What will change** - I will add code

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Java

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by joel1794** [comment]
I would like to work on this issue

**Comment by dipanshu1002** [comment]
Please assign this issue to me. Well documented code.

**Comment by SSKale1** [comment]
This problem already exists in the codebase.
