### ISSUE TITLE
1019 | Next Greater Node In Linked List | C++

### ISSUE THREAD

**Issue by jaisai6** [SHY-Corp/LeetCode-Solutions#1234]
## **`Title`** - Next Greater Node In Linked List

**What will change** - Solution will be added to the repo

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by jaisai6** [comment]
Please assign this issue and I have already solved this....

**Comment by SSKale1** [comment]
This problem already exists in the codebase.
