### ISSUE TITLE
Problem Number 16 |3 Sum Closest| C++

### ISSUE THREAD

**Issue by vibhutikathuria** [SHY-Corp/LeetCode-Solutions#1237]
Add solution to problem number 16 where in you have to find the closest sum of 3 numbers out of an array given a target input

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [ ] Python
- [x] C++
- [ ] Java
- [ ] SQL

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by rematchka** [comment]
Please assign this issue to me @SSKale1 @swaingotnochill @JOKUE2002 @Yashica7

**Comment by adarshraghav** [comment]
I could add a python solution for this problem, if it is still required. if so, can you also assign it to me

**Comment by SSKale1** [comment]
Issue already exists #1078
