### ISSUE TITLE
143 | Reorder List | C++ 

### ISSUE THREAD

**Issue by Himalay12** [SHY-Corp/LeetCode-Solutions#1238]
## 143. Reorder List.cpp

**What will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by chiillax** [comment]
Could you please assign me for this task ?

**Comment by Himalay12** [comment]
How do to assign?

**Comment by Himalay12** [comment]
how will i assign? i want to merge my code.

**Comment by Yashica7** [comment]
Make sure you wait for it to be assigned by the Maintainers of this Repository from now
