### ISSUE TITLE
763 | Partition Labels | C++ 

### ISSUE THREAD

**Issue by Himalay12** [SHY-Corp/LeetCode-Solutions#1239]
## 763.Partition Labels.cpp

**What will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by chiillax** [comment]
Could you please assign me for this task ?

**Comment by Himalay12** [comment]
yes you can.

> Could you please assign me for this task ?

i didn't get it

**Comment by Himalay12** [comment]
Hello, Are you there?

**Comment by chiillax** [comment]
Please review & merge #1243

**Comment by Himalay12** [comment]
I had open issue for my own contribution. I am here to contribute also.
