### ISSUE TITLE
1305 | All Elements in Two Binary Search Trees | C++

### ISSUE THREAD

**Issue by Himalay12** [SHY-Corp/LeetCode-Solutions#1240]
## 1305. All Elements in Two Binary Search Trees.cpp

**What will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by Oratoccio** [comment]
Hello, I would like to contribute to this.

**Comment by Himalay12** [comment]
I have already done pull request for
this.

**Comment by SSKale1** [comment]
This problem already exists in the codebase.

**Comment by Himalay12** [comment]
when i made it was not there.

**Comment by SSKale1** [comment]
It must've been an existing issue that was merged afterwards. Also check the existing issues while making new issues.

**Comment by Himalay12** [comment]
ok. From next tme i will take care of it.

**Comment by SSKale1** [comment]
No worries.
