### ISSUE TITLE
477 | Total Hamming Distance | C++

### ISSUE THREAD

**Issue by Vicky-Jha** [SHY-Corp/LeetCode-Solutions#125]
## **`Title`** - Total Hamming Distance

**What will change** - Add Solution
 
### Type of Issue - Adding New Code

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Code
- [x] Improving Documentation
- [x] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by Vicky-Jha** [comment]
Please assign me this issue @SSKale1

**Comment by Yashica7** [comment]
@Vicky-Jha Assigning it to u for now, but from next time please wait to get assigned before you make a pull request

**Comment by Vicky-Jha** [comment]
Yes, i understood @Yashica7

**Comment by hjpassion** [comment]
please assign it to me @SSKale1
