### ISSUE TITLE
1221 | Split a String in Balanced Strings  | Python

### ISSUE THREAD

**Issue by varian97** [SHY-Corp/LeetCode-Solutions#1254]
## **`Title`** - Split a String in Balanced Strings

**What will change** - I will add new code

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by Sameer-Mann** [comment]
@varian97  could i work on this?

**Comment by varian97** [comment]
@SSKale1 I didn't see anyone solved this problem yet, so I want to solved it. Can you please assign me to this issue? thanks

**Comment by varian97** [comment]
> @varian97 could i work on this?

I don't think so, you need to create a new issue for yourself, specifying the problem you want to solve and make sure no one has solved it

**Comment by varian97** [comment]
Waiting someone from the contributors team to assign me to this issue, so my PR counted as valid
