### ISSUE TITLE
1572 | Matrix Diagonal Sum | C++

### ISSUE THREAD

**Issue by vkc8181** [SHY-Corp/LeetCode-Solutions#1256]
## Matrix Diagonal Sum

**What will change** -
Adding new leetcode problem with solution in C++
### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by gitrahulgit** [comment]
I want to work!!

**Comment by vkc8181** [comment]
Please assign this to me :)

**Comment by Nusart** [comment]
@vkc8181 I am interested to work on this, please assign this to me.
