### ISSUE TITLE
1290 | Convert Binary Number in a Linked List to Integer | C++

### ISSUE THREAD

**Issue by vkc8181** [SHY-Corp/LeetCode-Solutions#1257]
## Convert Binary Number in a Linked List to Integer

**What will change** -
Adding a new leetcode problem with optimized c++ solution
### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by vkc8181** [comment]
Please assign this to me

**Comment by vaibhav1865** [comment]
Hello there,
Please assign this to me
