### ISSUE TITLE
595 | Big Countries | SQL

### ISSUE THREAD

**Issue by vkc8181** [SHY-Corp/LeetCode-Solutions#1259]
## Big Countries

**What will change** -
Adding a new Leetcode problem with SQL optimized solution 
### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

-[x] SQL

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by vkc8181** [comment]
Please assign this to me :) :)

**Comment by Piyush228** [comment]
@vkc8181 please assign this me :)

**Comment by Nusart** [comment]
@vkc8181 I am interested to work on this project, please assign this to me.
