### ISSUE TITLE
201.| Bitwise AND of Numbers Range | c++

### ISSUE THREAD

**Issue by champ96k** [SHY-Corp/LeetCode-Solutions#1278]
## **`Bitwise AND of Numbers Range`** -

**What will change** - written a c++ code

### Type of Issue - Solve question

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Code
- [x] Improving Documentation
- [ ] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [ ] Python
- [x] C++
- [ ] Java
- [ ] SQL

### Self Check 

- [x] Ask for an issue assignment and wait to get assigned to it before making Pull Request.
- [x] Add your file to the proper folder
- [x] `Clean Code` and `Documentation` for better readability
- [x] Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by gitrahulgit** [comment]
I would like to work on it!!

**Comment by champ96k** [comment]
I already solve this question :
 https://github.com/SHY-Corp/LeetCode-Solutions/pull/1277/commits/792e8d2093229ddd4a0dfddba6c6221f993f870f
