### ISSUE TITLE
389. | Find the Difference | c++

### ISSUE THREAD

**Issue by champ96k** [SHY-Corp/LeetCode-Solutions#1281]
## **`389. | Find the Difference | c++`** -

**What will change** - 

### Type of Issue - question

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Code
- [x] Improving Documentation
- [ ] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [ ] Python
- [x] C++
- [ ] Java
- [ ] SQL

### Self Check 

- [x] Ask for an issue assignment and wait to get assigned to it before making Pull Request.
- [x] Add your file to the proper folder
- [x] `Clean Code` and `Documentation` for better readability
- [x] Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by chiillax** [comment]
Could you please assign me for this task ?

**Comment by Manojsingh929** [comment]
i want to work upon it
plz assign it to me

**Comment by srk224** [comment]
Assign me this issue.
