### ISSUE TITLE
749 |  Contain Virus | Java

### ISSUE THREAD

**Issue by jag-singh-96** [SHY-Corp/LeetCode-Solutions#1283]
## **` Contain Virus`** -

**What will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Java

### Self Check 

- Ask for an issue assignment and wait to get assigned to it before making Pull Request.
- Add your file to the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by jag-singh-96** [comment]
Please assign this issue to me.

**Comment by SSKale1** [comment]
@jag-singh-96 why are you creating duplicate issue of the problem you've been assigned to. #1034
