### ISSUE TITLE
476 | Number Complement | C++

### ISSUE THREAD

**Issue by champ96k** [SHY-Corp/LeetCode-Solutions#1284]
### Type of Issue - question

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Code
- [x] Improving Documentation
- [ ] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [ ] Python
- [x] C++
- [ ] Java
- [ ] SQL

### Self Check 

- [x] Ask for an issue assignment and wait to get assigned to it before making Pull Request.
- [x] Add your file to the proper folder
- [x] `Clean Code` and `Documentation` for better readability
- [x] Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by sourabhjain9887** [comment]
please assign me this issue.

**Comment by manilal-1084** [comment]
Could you assign this issue to me?
