### ISSUE TITLE
9| Palindrome Number| Python

### ISSUE THREAD

**Issue by DOCTSTR** [SHY-Corp/LeetCode-Solutions#129]
## **`9| Palindrome Number| Python`** -

**What will change** -
Added Python solution to the LeetCode problem: 9. Palindrome Number
### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] Python

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by DOCTSTR** [comment]
Can you assign this to me?
Thanks

**Comment by utkarsh48** [comment]
I want to contribute to this!

**Comment by samjones246** [comment]
I'd like to be assigned to this please :)

**Comment by OMEGAeNcore** [comment]
Please assign me to this

**Comment by hjpassion** [comment]
please assign me some tasks

**Comment by prikshitsetia** [comment]
Hey I would like to contribute to this

**Comment by SSKale1** [comment]
- [x] Assigned to @DOCTSTR for issue creation.
