### ISSUE TITLE
506 | Relative Ranks | C++

### ISSUE THREAD

**Issue by vivaswat19** [SHY-Corp/LeetCode-Solutions#1294]
### Type of Issue - Question

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by vivaswat19** [comment]
Please assign this issue to me.

**Comment by sourabhjain9887** [comment]
please assign me this issue.

**Comment by vivaswat19** [comment]
@SSKale1 please review my PR.
Thank you.
