### ISSUE TITLE
1436 | Destination City| Python

### ISSUE THREAD

**Issue by PraneshUlleri** [SHY-Corp/LeetCode-Solutions#1296]
### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] Python

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by PraneshUlleri** [comment]
I would like to work on this code

**Comment by AlexandreOkita** [comment]
I would like to contribute! Please assign me this issue.
