### ISSUE TITLE
1351 | Count Negative Numbers in a Sorted Matrix | Python

### ISSUE THREAD

**Issue by PraneshUlleri** [SHY-Corp/LeetCode-Solutions#1303]
## **`Count Negative Numbers in a Sorted Matrix`** -

**What will change** -

Adding Solution to above problem

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by PraneshUlleri** [comment]
I would like to work on this issue

**Comment by sourabhjain9887** [comment]
I would like to contribute , please assign me this issue.
