### ISSUE TITLE
927 |Three Equal Parts | C++

### ISSUE THREAD

**Issue by 0ChanAk** [SHY-Corp/LeetCode-Solutions#1315]
## **`Title`** - 927. Three Equal Parts. C++

**What will change** - new code

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [] Python
- [x] C++
- [] Java
- [] SQL

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by gitrahulgit** [comment]
I want to work on it

**Comment by prantoran** [comment]
Could you please assign this issue to me?

**Comment by subhadeep-123** [comment]
i would like to solve this issue..can you please assign me this issue
