### ISSUE TITLE
27 | Remove Element | Python

### ISSUE THREAD

**Issue by Azanul** [SHY-Corp/LeetCode-Solutions#1316]
## **`Title`** -

**Single optimum solution** -

### Type of Issue -

Please add/delete options that are not relevant.

- [ ] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [x] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [x] Python
- [ ] C++
- [ ] Java
- [ ] SQL

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by amandou** [comment]
Can I do this issue in C++?

**Comment by Azanul** [comment]
> Can I do this issue in C++?

You do realise that this is a bug fix i.e., there are multiple solutions to the same question.

**Comment by vivekshah1801** [comment]
@Azanul can i work on this?

**Comment by ghanender-chauhan** [comment]
i want to dothis assign me
