### ISSUE TITLE
215 | Kth Largest Element in an Array | Python

### ISSUE THREAD

**Issue by OMEGAeNcore** [SHY-Corp/LeetCode-Solutions#132]
## **`Title`** - 215. Kth Largest Element in an Array

**What will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python
- [x] Java
- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by OMEGAeNcore** [comment]
Please assign me this.

**Comment by hjpassion** [comment]
please assign atleast this one with me because i m  not able to get any of the tasks

**Comment by SSKale1** [comment]
- [x] Assigned to @OMEGAeNcore for issue creation.

**Comment by SSKale1** [comment]
@hjpassion we've assigned you an issue.
