### ISSUE TITLE
221 | Maximal Square| C++

### ISSUE THREAD

**Issue by Shobhit-aryan** [SHY-Corp/LeetCode-Solutions#1324]
## **`Maximal Square`** -

**What will change** -
Adding solution
### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language
C++
Please add/delete options that are not relevant.

- [x] C++

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by Shobhit-aryan** [comment]
Please assign this to me

**Comment by prantoran** [comment]
Could you please assign this issue to me?
