### ISSUE TITLE
001 to 239 | Support C Language | C

### ISSUE THREAD

**Issue by lin826** [SHY-Corp/LeetCode-Solutions#1341]
## **`Support C Language`** -

Add [another leetcode solution repo in C](https://github.com/begeekmyfriend/leetcode) with [git submodule](https://github.blog/2016-02-01-working-with-submodules/)

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Documentation

### Programming Language

Please add/delete options that are not relevant.

- [x] C

### Proposed Implementation

git submodule as in [this commit](https://github.com/lin826/LeetCode-Solutions/commit/68f2180d2ffe3d29dc719d0a2fa87d41f2e6450a)

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by SSKale1** [comment]
@lin826 Thats a good Idea to add C to the mix but we'll do it after some time, currently overflowing with hacktoberfest creations. And secondly I don't think that this project is sufficiently complex to need git submodules. we can just work with another directory for C as we have for C++, Java, Python and SQL.
