### ISSUE TITLE
116 | Populating Next Right Pointers in Each Node | C++

### ISSUE THREAD

**Issue by parvezaalam786** [SHY-Corp/LeetCode-Solutions#1349]
## **`Populating Next Right Pointers in Each Node`** -

**What will change** -

### Type of Issue 

- [x] Adding New Code

### Programming Language
- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by parvezaalam786** [comment]
Please assign this to me. 
I will explain this problem by two methods with proper documentation and code in C++.

**Comment by SSKale1** [comment]
Duplicate of issue #818
