### ISSUE TITLE
38 | Count and Say | C++

### ISSUE THREAD

**Issue by hjpassion** [SHY-Corp/LeetCode-Solutions#135]
## **`Title`** -

**What will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Code
- [x] Improving Documentation
- [x] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by hjpassion** [comment]
please assign me this issue @SSKale1

**Comment by sunil-17112** [comment]
please assign me this issue

**Comment by sark-2110** [comment]
Can you assign me this issue?  I have solved the problem and have a good solution for it in C++.

**Comment by Shashank2409** [comment]
Could you please assign me for this one? I have a C++ recursive code for this problem. My code runs faster than 100% of the cpp solutions and beats the memory usage of 53.79% of cpp solutions on Leetcode.

**Comment by tejasbhale** [comment]
Kindly assign me this issue. I have an optimal C++ solution for this and since I'm new to open source, I'd like to start by contributing somewhere. Thank you!

**Comment by SSKale1** [comment]
- [x] Assigning to @hjpassion for issue creation

**Comment by SSKale1** [comment]
@tejasbhale   you can create your own issue there are a lot of problems out there. Just go through the contribution guidelines.

**Comment by sabrajsab** [comment]
if it is still open issue, please assign it to me. I have an efficient solution in c++
