### ISSUE TITLE
227 | Basic Calculator II | Python

### ISSUE THREAD

**Issue by kakashi215** [SHY-Corp/LeetCode-Solutions#1355]
## **`Basic Calculator II`** -

**What will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by kakashi215** [comment]
Requesting to be assigned to the issue to contribute to the repo.

Cheers!

**Comment by kakashi215** [comment]
> Requesting to be assigned to the issue to contribute to the repo.
> 
> Cheers!

@SSKale1 
@Yashica7 
@swaingotnochill 
@JOKUE2002

**Comment by subhadeep-123** [comment]
can i solve this issue

**Comment by kakashi215** [comment]
@subhadeep-123 
I'd recommend you to open up your own issue and request to be assigned to it.
I mean that's the official way to contribute.

Cheers!

**Comment by subhadeep-123** [comment]
OKAY COOL !!!
