### ISSUE TITLE
7331| Most-Consecutive 1's in an Array| Language

### ISSUE THREAD

**Issue by Mrinal-Choudhary07** [SHY-Corp/LeetCode-Solutions#1356]
## **`Most-Consecutive 1's`** -

**What will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Java

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by Mrinal-Choudhary07** [comment]
Please assign me this issue, I'm ready

**Comment by SSKale1** [comment]
Please go through the [Contribution Guidelines](https://github.com/SHY-Corp/LeetCode-Solutions/blob/master/CONTRIBUTING.md)

**Comment by Ani1000** [comment]
@SSKale1 but then this was not assigned to any body I guess . may I take this work as we are running out of time
