### ISSUE TITLE
1572 | Matrix Diagonal Sum | C++

### ISSUE THREAD

**Issue by ViKrAm-Bais** [SHY-Corp/LeetCode-Solutions#1368]
## **`Matrix Diagonal Sum`** -

**What will change** -
Adding code for calculating sum of all the elements on the primary diagonal and all the elements on the secondary diagonal that are not part of the primary diagonal.

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [ ] Python
- [x] C++
- [ ] Java
- [ ] SQL

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by ViKrAm-Bais** [comment]
could you assign it to me, I have solution for this

**Comment by SSKale1** [comment]
Duplicate Issue #1256
