### ISSUE TITLE
88 | Merge Sorted Array | C++

### ISSUE THREAD

**Issue by ViKrAm-Bais** [SHY-Corp/LeetCode-Solutions#1369]
## **`Merge Sorted Array`** -

**What will change** -
 Adding code for merging two sorted arrays

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [ ] Python
- [x] C++
- [ ] Java
- [ ] SQL

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by ViKrAm-Bais** [comment]
Could you assign it to me, I have to do this ?

**Comment by Himalay12** [comment]
I want to contribute for this issue. Could you assign it to me.
