### ISSUE TITLE
1290 | Convert Binary Number in a Linked List to Integer | Python

### ISSUE THREAD

**Issue by PraneshUlleri** [SHY-Corp/LeetCode-Solutions#1375]
### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by PraneshUlleri** [comment]
Can I work on this issue?

**Comment by SSKale1** [comment]
Duplicate #1257

**Comment by PraneshUlleri** [comment]
this is solution in python
