### ISSUE TITLE
19 | Remove Nth Node From End of List| C++

### ISSUE THREAD

**Issue by Himalay12** [SHY-Corp/LeetCode-Solutions#1378]
## 19. Remove Nth Node From End of List.cpp

**What will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by Himalay12** [comment]
Assign me i want to contribute for this problem.

**Comment by SSKale1** [comment]
Duplicate issue #447

**Comment by Himalay12** [comment]
How do we check if the issue is present or not.

**Comment by Himalay12** [comment]
i found that solution is not there

**Comment by SSKale1** [comment]
In the issues tab you can search for the problem number. It will show up all the other issues created for the search query.

**Comment by Himalay12** [comment]
Assign me for issue for problem 39. It is not there in cpp. I want to
contribute it.
