### ISSUE TITLE
1234 | Intersection of two Linked-Lists | Java

### ISSUE THREAD

**Issue by Mrinal-Choudhary07** [SHY-Corp/LeetCode-Solutions#1389]
## **`Intersection of two Linked-Lists`** -

**What will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Java

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by Mrinal-Choudhary07** [comment]
As we have 2 more days in hacktoberfest, please assign this issue to me.

**Comment by SSKale1** [comment]
Problem [1234](https://leetcode.com/problems/replace-the-substring-for-balanced-string/) is a different problem.
