### ISSUE TITLE
633| Sum of Square Numbers| C++

### ISSUE THREAD

**Issue by Ani1000** [SHY-Corp/LeetCode-Solutions#1392]
## **`Title`** -

**What will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Code
- [x] Improving Documentation
- [x] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [ ] Python
- [x] C++
- [ ] Java
- [ ] SQL

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by Janhavi-Gautam** [comment]
Hey , I want to work on this issue. Can you assign it to me?

**Comment by Ani1000** [comment]
> Hey , I want to work on this issue. Can you assign it to me?

Sorry mam actually I prepared for the solutions and raised the issuse hence do the same

**Comment by SSKale1** [comment]
This problem already exists in the codebase.
