### ISSUE TITLE
5 | Longest Palindromic Substring | C++

### ISSUE THREAD

**Issue by DarkWarrior703** [SHY-Corp/LeetCode-Solutions#14]
## **`Title`** -

**What will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language
- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/Ftbj4a

Happy Coding,

**Comment by danieljo09** [comment]
Hi Can I work on this?

**Comment by SSKale1** [comment]
@danieljo09 this issue will be assigned to @DarkWarrior703 you can create another issue for any other problem. Just make sure you read and follow the contribution Guidelines.

**Comment by Yashica7** [comment]
@DarkWarrior703 We'll be assigning this issue to u for now, please wait for the assignment before pulling a request from next time, Thanks
