### ISSUE TITLE
206. | Reverse Linked List | C++

### ISSUE THREAD

**Issue by juhikushwah** [SHY-Corp/LeetCode-Solutions#1401]
## **`Title`** - Solution for Reverse Linked List in C++

**What will change** -

### Type of Issue - Adding solution for 66. Reverse Linked List in C++

Please add/delete options that are not relevant.

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [ ] Python
- [x] C++
- [ ] Java
- [ ] SQL

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by juhikushwah** [comment]
Please assign this issue to me.

**Comment by purva-saxena** [comment]
please assign this task to me! i have already solved it

**Comment by ViKrAm-Bais** [comment]
Can I solve this issue, I can have an solution with O(n) time complexity

**Comment by juhikushwah** [comment]
@SSKale1 Hi, could you please assign this one to me. Thank you.
