### ISSUE TITLE
896. | Monotonic Array | C++

### ISSUE THREAD

**Issue by juhikushwah** [SHY-Corp/LeetCode-Solutions#1403]
## **`Title`** - Solution for Monotonic Array in C++

**What will change** -  Adding solution for 896. Monotonic Array in C++

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by juhikushwah** [comment]
Please assign this to me!

**Comment by Janhavi-Gautam** [comment]
Hey, I would like to work on this issue . Can you assign it to me?
