### ISSUE TITLE
69 | Sqrt(x) | C++

### ISSUE THREAD

**Issue by jDerp** [SHY-Corp/LeetCode-Solutions#1405]
## **`Title`** - Solution for Problem 69 in C++

**What will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by jDerp** [comment]
Assign to me please?

**Comment by Debadri3** [comment]
Please assign to me.

**Comment by Debadri3** [comment]
@jDerp

**Comment by jDerp** [comment]
Duplicate
