### ISSUE TITLE
22 | Generate Parentheses| Java

### ISSUE THREAD

**Issue by shevya06** [SHY-Corp/LeetCode-Solutions#141]
Generate Parentheses

### Type of Issue -

- [x] Adding New Code

**Programming language**

- [x] Java

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by shevya06** [comment]
I would like to contribute this

**Comment by PrinceKhatick** [comment]
I would like to contribute to this ...

**Comment by SSKale1** [comment]
- [x] Assigning to @shevya06 for issue creation.
