### ISSUE TITLE
876. | Middle of the Linked List | C++

### ISSUE THREAD

**Issue by juhikushwah** [SHY-Corp/LeetCode-Solutions#1416]
## **`Title`** - Solution for Middle of the Linked List

**What will change** - Adding solution for 876 Middle of the Linked List in C++

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by juhikushwah** [comment]
Please assign this to me!

**Comment by sumo1998** [comment]
Please assign this to me

**Comment by juhikushwah** [comment]
@SSKale1 Please assign me this!

**Comment by commitedlearner** [comment]
please assign me this:)
