### ISSUE TITLE
709 | To Lower Case | C++

### ISSUE THREAD

**Issue by vkc8181** [SHY-Corp/LeetCode-Solutions#1422]
## To Lower Case

**What will change** -
Will add a C++ optimized solution for this LeetCode problem.
### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by vkc8181** [comment]
Kindly assign this to me. Thanks :)

**Comment by Debadri3** [comment]
Can you assign this to me?

**Comment by commitedlearner** [comment]
please assign me this issue:)
