### ISSUE TITLE
1520 | Maximum Number of Non-Overlapping Substrings | C++

### ISSUE THREAD

**Issue by adish-dev** [SHY-Corp/LeetCode-Solutions#1424]
## **`Maximum Number of Non-Overlapping Substrings`** -

**What will change** -

Coding file is uploaded 

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by adish-dev** [comment]
I'd like to contribute!
Please merge after checking

**Comment by Yashica7** [comment]
Assigned it to you for now, next time onward you first need to wait to get assigned before making any pull requests else it could be marked invalid
