### ISSUE TITLE
Problem Number | Title | Language

### ISSUE THREAD

**Issue by sumo1998** [SHY-Corp/LeetCode-Solutions#1431]
## **`Title`** - Solution for Subtree of Another Tree

**What will change** - Adding solution for 572

### Type of Issue -

Please add/delete options that are not relevant.

- Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by sumo1998** [comment]
Please Issue this to me

**Comment by SSKale1** [comment]
@sumo1998 you have to create a PR only after you've been assigned to the issue. We'll be closing this now. Please go through the [contribution guidelines.](https://github.com/SHY-Corp/LeetCode-Solutions/blob/master/CONTRIBUTING.md)

**Comment by SSKale1** [comment]
@sumo1998 change the title according to the [contribution guidelines.](https://github.com/SHY-Corp/LeetCode-Solutions/blob/master/CONTRIBUTING.md)
