### ISSUE TITLE
20. Valid Parentheses | C++

### ISSUE THREAD

**Issue by tejasbhale** [SHY-Corp/LeetCode-Solutions#144]
### Type of Issue -

- [x] Adding New Code
- [x] Improving Code
- [x] Improving Documentation
- [x] Bug Fix

### Programming Language -

- [x]  C++

### Self Check 

- [x]  Ask for issue assignment and wait to get assigned to it before making Pull Request.

- [x] Add your file in the proper folder

- [x] `Clean Code` and `Documentation` for better readability

- [x] Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding

**Comment by tejasbhale** [comment]
please assign me to this issue

**Comment by CormacKrum** [comment]
Please Assign This to me In Java

**Comment by sabrajsab** [comment]
please assign me this issue in c++

**Comment by Francode007** [comment]
Please assign this to me in c++
(concise stack solution+improved documentation)
