### ISSUE TITLE
287 | Find the Duplicate Number | C++

### ISSUE THREAD

**Issue by juhikushwah** [SHY-Corp/LeetCode-Solutions#1447]
## **`Title`** - Solution for Find the Duplicate Number

**What will change** - Adding code for 287. Find the Duplicate Number in C++

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by juhikushwah** [comment]
@SSKale1  Please assign me this task.

**Comment by commitedlearner** [comment]
please assign me this task ;)

**Comment by Janhavi-Gautam** [comment]
Hey , Can you assign me this work?
