### ISSUE TITLE
162. Find Peak Element | C++

### ISSUE THREAD

**Issue by Ani1000** [SHY-Corp/LeetCode-Solutions#1470]
## **`Title`** -

**What will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Code
- [x] Improving Documentation
- [x] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [x] Python
- [x] C++
- [x] Java
- [x] SQL

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by Ani1000** [comment]
@SSKale1 Sir please assign me this issue

**Comment by khavinshankar** [comment]
please assign me this issue, I have a solution with 98% better runtime and 100% better space.

**Comment by Ani1000** [comment]
> @khavinshankar please assign me this issue, I have a solution with 98% better runtime and 100% better space.

Please refer to the community guide lines before commiting. also please try to raise a new issues hope that helps

**Comment by SSKale1** [comment]
Duplicate issue #1077
