### ISSUE TITLE
1590 | Check whether tree is full binary tree or not | Java 

### ISSUE THREAD

**Issue by nitish166** [SHY-Corp/LeetCode-Solutions#1482]
## **`Title`** -

**What will change** -

### Type of Issue - comment written on the code

Please add/delete options that are not relevant.

- [x] Improving Documentation

### Programming Language

Please add/delete options that are not relevant.

- [x] Java

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by AmeyaPhadnis-2019H1030012G** [comment]
Please assign this issue to me, I am new to open source and would like to contribute

**Comment by SSKale1** [comment]
Duplicate #1474
