### ISSUE TITLE
84 | Maximum Area Histogram | Python

### ISSUE THREAD

**Issue by kaushalendra-pandey** [SHY-Corp/LeetCode-Solutions#1498]
## **`Title`** - maximumAreaHistogram

**What will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by RaymondWaterlooLi** [comment]
May I work on this issue?  Could you please assign it to me?

**Comment by kaushalendra-pandey** [comment]
> May I work on this issue? Could you please assign it to me?

Yeah sure!!!

**Comment by SSKale1** [comment]
@kaushalendra-pandey Please go through the [contribution guidelines.](https://github.com/SHY-Corp/LeetCode-Solutions/blob/master/CONTRIBUTING.md) And edit the title accordingly.

**Comment by SSKale1** [comment]
- [x] Assigning to @RaymondWaterlooLi

**Comment by RaymondWaterlooLi** [comment]
> * [x]  Assigning to @RaymondWaterlooLi

Thank you.
