### ISSUE TITLE
1277|  Count Square Submatrices with All Ones | Python

### ISSUE THREAD

**Issue by kaushalendra-pandey** [SHY-Corp/LeetCode-Solutions#1501]
## **`Title`** -countSquareSubMatricesWithAllOnes

**What will change** - I will add a solution to this problem

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by AmeyaPhadnis-2019H1030012G** [comment]
Please assign this issue to me, I am new to open source and looking for opportunities to contribute
