### ISSUE TITLE
1414 | Find the Minimum Number of Fibonacci Numbers Whose Sum Is K | Python

### ISSUE THREAD

**Issue by kaushalendra-pandey** [SHY-Corp/LeetCode-Solutions#1526]
1414. Find the Minimum Number of Fibonacci Numbers Whose Sum Is K

**What will change** - I wiil add a new code in the PYTHON folder

### Type of Issue - Solving a new problem

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by Yashica7** [comment]
- [x] Assigned to @kaushalendra-pandey
