### ISSUE TITLE
563 | Binary Tree Tilt | C++

### ISSUE THREAD

**Issue by khavinshankar** [SHY-Corp/LeetCode-Solutions#1530]
## **`Title`** - 563. Binary Tree Tilt

**What will change** - add a new file with a solution for 563. Binary Tree Tilt in C++

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by khavinshankar** [comment]
please assign me this issue

**Comment by Yashica7** [comment]
- [x] Assigned to @khavinshankar
