### ISSUE TITLE
867 | Transpose Matrix | C++

### ISSUE THREAD

**Issue by khavinshankar** [SHY-Corp/LeetCode-Solutions#1536]
## **`Title`** - 867. Transpose Matrix

**What will change** - adding a new file with a solution for 867. Transpose Matrix in C++

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by khavinshankar** [comment]
please assign me this issue

**Comment by Sauravsingh-Rana** [comment]
please assign me this issue

**Comment by khavinshankar** [comment]
> please assign me this issue
@Sauravsingh-Rana **to contribute,**

1. Choose a leetcode problem that is not already present.
2. Create an issue and wait for it to be assigned to you.
3. Create a pull request.
for more info [check this out](https://github.com/SHY-Corp/LeetCode-Solutions/blob/master/CONTRIBUTING.md).

**Comment by Sauravsingh-Rana** [comment]
I can give it a shot, to your transpose matrix issue.
Wave green signal so that I can move forward. **@khavinshankar**

**Comment by khavinshankar** [comment]
> I can give it a shot, to your transpose matrix issue.
> Wave green signal so that I can move forward. **@khavinshankar** 

@Sauravsingh-Rana ya sure 👍🏻

**Comment by Sauravsingh-Rana** [comment]
> > I can give it a shot, to your transpose matrix issue.
> > Wave green signal so that I can move forward. **@khavinshankar**
> 
> @Sauravsingh-Rana ya sure 👍🏻
> But wait for this request to be assigned to you before making the pull request.

Sure...**@khavinshankar**
