### ISSUE TITLE
709 | To Lower Case | C++

### ISSUE THREAD

**Issue by khavinshankar** [SHY-Corp/LeetCode-Solutions#1538]
## **`Title`** - 709. To Lower Case

**What will change** - adding a new file with a solution for 709. To Lower Case in C++

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by khavinshankar** [comment]
please assign me this issue

**Comment by anands97** [comment]
Can you please assign me this issue?

**Comment by khavinshankar** [comment]
> Can you please assign me this issue?
@anands97 **to contribute,**

1. Choose a leetcode problem that is not already present.
2. Create an issue and wait for it to be assigned to you.
3. Create a pull request.
for more info [check this out](https://github.com/SHY-Corp/LeetCode-Solutions/blob/master/CONTRIBUTING.md).
