### ISSUE TITLE
136 | Single Number | C++

### ISSUE THREAD

**Issue by juhikushwah** [SHY-Corp/LeetCode-Solutions#1552]
## **`Title`** - C++ code for 136. Single Number

**What will change** - Adding code in C++ for leetcode question 136

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by juhikushwah** [comment]
@SSKale1 
@Yashica7 
@JOKUE2002 
@swaingotnochill 

Please assign this to me.

**Comment by Arjun-Zaraki** [comment]
@JOKUE2002 
@Yashica7 
@SSKale1 
@swaingotnochill 

Can u please assign this issue to me.
