### ISSUE TITLE
744 | Find Smallest Letter Greater Than Target | C++

### ISSUE THREAD

**Issue by juhikushwah** [SHY-Corp/LeetCode-Solutions#1554]
## **`Title`** - C++ code for 744. Find Smallest Letter Greater Than Target

**What will change** - Adding C++ code for leetcode problem 744

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] C++

**Comment by juhikushwah** [comment]
@SSKale1 @Yashica7 @JOKUE2002 @swaingotnochill 

Please assign this to me.

**Comment by Ankur6702** [comment]
Hello
I wanted to contribute in this issue. Can you please guide how can I contribute to it.

**Comment by juhikushwah** [comment]
@Ankur6702 Hi. So, you create your own issue and ask the admin to assign you that task.  Look for leetcode problems that haven't already been solved and check if they are there in the issues column. If not present, you can pick that problem.

**Comment by Ankur6702** [comment]
Please guide what kind of issue I can create on my own. I am new in Github so need a bit support.

**Comment by juhikushwah** [comment]
You could checkout the readme file. It has all the details!
