### ISSUE TITLE
1492 | The kth Factor of n | C++

### ISSUE THREAD

**Issue by khavinshankar** [SHY-Corp/LeetCode-Solutions#1588]
## **`Title`** - 1492. The kth Factor of n

**What will change** - adding a new file with a solution for 1492. The kth Factor of n in C++

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by khavinshankar** [comment]
please assign me this issue

**Comment by vipul-2003** [comment]
Please assign this to me 🤗

**Comment by vipul-2003** [comment]
@juhikushwah  please assign it to me

**Comment by vipul-2003** [comment]
i am working on this thanks :heart:

**Comment by vipul-2003** [comment]
have a look @juhikushwah
