### ISSUE TITLE
327 | Armstrong Number | C++

### ISSUE THREAD

**Issue by AnshTandon0** [SHY-Corp/LeetCode-Solutions#1612]
## **`Title`** - C++ code for 327. Armstrong Number

**What will change** -Adding C++ code for leetcode problem 327

### Programming Language - C++

**Comment by AnshTandon0** [comment]
please assign this to me

**Comment by vipul-2003** [comment]
Please assign this to me .

**Comment by nisthajnn** [comment]
please assign this to me

**Comment by vipul-2003** [comment]
@juhikushwah  please assign it to me

**Comment by vipul-2003** [comment]
i am working on it thanks ❤️

**Comment by vipul-2003** [comment]
merge request #1688 
Have a look at this,
 thanks ❤️

**Comment by juhikushwah** [comment]
@vipul-2003 your solution is fine. I think this is a premium problem. It's not 372 or 327. I just checked, the problem number is 1134. Enclosing a link for your reference: https://leetcode.ca/all/1134.html
Please rename it to **1134.ArmstrongNumber.cpp**. I don't want to mess up with your existing branch so make your changes accordingly and push them.

**Comment by vipul-2003** [comment]
Ok , i will rename it 
Thanks ♥️
