### ISSUE TITLE
ArraySub | C++

### ISSUE THREAD

**Issue by JayantGoel001** [SHY-Corp/LeetCode-Solutions#1613]
## **`ArraySub`** -

**What will change** -

### Type of Issue - Use of  Deque and sliding window

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by vvishnu17** [comment]
Please assign this to me

**Comment by vipul-2003** [comment]
I am beginner there but as i know that it's my first program .So please give a chance to prove my self .
