### ISSUE TITLE
1171 | Remove Zero Sum Consecutive Nodes from Linked List | C++

### ISSUE THREAD

**Issue by juhikushwah** [SHY-Corp/LeetCode-Solutions#1615]
## **`Title`** - C++ code for 1171. Remove Zero Sum Consecutive Nodes from Linked List

**What will change** - Adding C++ solution for leetcode problem 1171

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] C++

**Comment by juhikushwah** [comment]
Please assign this to me.

**Comment by aditya28sarin** [comment]
Hey, can you assign this issue to me, I have worked on this problem

**Comment by juhikushwah** [comment]
@aditya28sarin Hi. You need to create your own issues and then ask the admins to assign it to you. Read the guidelines for more information.

**Comment by josh-dp** [comment]
Hi, can I be assigned this issue? It seems to not have been completed.
