### ISSUE TITLE
405 | Convert a Number to Hexadecimal | C++

### ISSUE THREAD

**Issue by ayushbisht2001** [SHY-Corp/LeetCode-Solutions#1626]
## **`Title`** - C++ code for 405 , Convert a Number to Hexadecimal

**What will change** - Adding C++ code for leetcode problem 405

### Type of Issue -
- [x] Adding New Code

### Programming Language
- [x] C++

**Comment by Gaurav-20** [comment]
I have added the code, please do check that

**Comment by ayushbisht2001** [comment]
Checkout the contribution guidelines ...... Becoz I didn't found any issue related to problem 405

**Comment by Gaurav-20** [comment]
The problem 405 was missing earlier so I added the same.

**Comment by ayushbisht2001** [comment]
@SSKale1 Please assign this to me.

**Comment by vipul-2003** [comment]
Please assign it to me @juhikushwah

**Comment by vipul-2003** [comment]
Hey ,@juhikushwah 

Please provide some detail for this if possible  like filename, leetcode question link ...?

**Comment by juhikushwah** [comment]
@vipul-2003 all the details are in the issue headline. Its not a premium problem. You will be able to see the problem description on leetcode.

**Comment by vipul-2003** [comment]
have a look at this @juhikushwah

**Comment by vipul-2003** [comment]
Give me few hours by next day the code will be at right position in c++ folder

**Comment by juhikushwah** [comment]
@vipul-2003 While merging, I did not realize it's in the wrong folder. Thank you for the update! And yes, please do make the relevant changes!

**Comment by juhikushwah** [comment]
Actually Vipul, the solution to this problem already exists in the C++ folder. If you think your solution is better than that one, you can push your code into that file and comment out the previous solution too, thereby mentioning that it's an optimal solution! We have this repository for solving problems as well as adding better/alternative solutions to already existing problems.

**Comment by vipul-2003** [comment]
Ok, i will review it ....
