### ISSUE TITLE
73 | Set Matrix Zeroes | C++

### ISSUE THREAD

**Issue by vipul-2003** [SHY-Corp/LeetCode-Solutions#1680]
## **`Title`** - Set Matrix 

**What will change** -
I would like to provide the solution to **`SET MATRIX ZEROES `**

Link :: [SET MARTIX ZEROES](https://leetcode.com/problems/set-matrix-zeroes/description/)

```text
Please assign it to me
```

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Code
- [x] Improving Documentation
- [x] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [ ] Python
- [X] C++
- [ ] Java
- [ ] SQL

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by nilnguyenkl** [comment]
Please assign this to me. Thanks

**Comment by vipul-2003** [comment]
@nilnguyenkl  you may create new issue ..... 😶

**Comment by juhikushwah** [comment]
@vipul-2003 issues are assigned to those who ask for it first. Please read the contributions guideline.

**Comment by vipul-2003** [comment]
> @vipul-2003 issues are assigned to those who ask for it first. Please read the contributions guideline. 

Hey thats not good , i have read the contributions rules and even also requested for assigning me clearly scene in large .... 😶😐

**Comment by vipul-2003** [comment]
> > @vipul-2003 issues are assigned to those who ask for it first. Please read the contributions guideline. 
> 
> Hey thats not good , i have read the contributions rules and even also requested for assigning me clearly scene in large .... 😶😐

Look at the issue raised

**Comment by juhikushwah** [comment]
@vipul-2003 when you create an issue, you also need to mention it in the comments that you want the issue to be assigned to you. You can look at all the previous issues. They were assigned to those who mentioned it first. It doesn't matter who raised that issue!

**Comment by vipul-2003** [comment]
> @vipul-2003 when you create an issue, you also need to mention it in the comments that you want the issue to be assigned to you. You can look at all the previous issues. They were assigned to those who mentioned it first. It doesn't matter who raised that issue! Also, please read the guidelines. 

No worry ....
