### ISSUE TITLE
367 | Valid Perfect Square | C++

### ISSUE THREAD

**Issue by vipul-2003** [SHY-Corp/LeetCode-Solutions#1684]
## **`Title`** -  [Valid Perfect Square](https://leetcode.com/problems/valid-perfect-square/)

**What will change** - Add solution to this question 

 
- [x] Adding New Code
- [x] Improving Code
- [x] Improving Documentation
- [x] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [ ] Python
- [X] C++
- [ ] Java
- [ ] SQL

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by vipul-2003** [comment]
please assign it to me @juhikushwah

**Comment by NgoQuocBao1010** [comment]
Hello, can I take this issue?

**Comment by vipul-2003** [comment]
Sorry ,  I have created the code for it just one step away from creating pr

**Comment by juhikushwah** [comment]
@NgoQuocBao1010 you can create your own issues and **mention it in the comments section** that you want them to be assigned. Currently, all issues are taken up. Generally, issues are assigned to the people who 1st mention it in the comments section irrespective of who created the issue. Please read the contributions guideline for more information.

**Comment by vipul-2003** [comment]
have a look at the code @juhikushwah  and merge into main 
thanks :heart:
