### ISSUE TITLE
Typos and grammar

### ISSUE THREAD

**Issue by wpedrak** [SHY-Corp/LeetCode-Solutions#169]
## **`Title`** - Typos and grammar

**What will change** - Fix `pull_request_template.md` and `CONTRIBUTING.md`

### Type of Issue - documentation/template fix

Please add/delete options that are not relevant.

- [ ] Adding New Code
- [ ] Improving Code
- [x] Improving Documentation
- [ ] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [ ] Python
- [ ] C++
- [ ] Java
- [ ] SQL

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by wpedrak** [comment]
Once creating PR my [gramarly](https://app.grammarly.com/) reported few issues. Might be nice to fix it.
(I'm not asking to assign me to it)

**Comment by SSKale1** [comment]
What issues were those @wpedrak

**Comment by wpedrak** [comment]
This is what I've spotted:
https://github.com/wpedrak/LeetCode-Solutions/commit/4f59ffbacdf8780fbad847eaf927c894b944d9d0

**Comment by SSKale1** [comment]
@wpedrak You can make a PR to make these corrections.

**Comment by wpedrak** [comment]
Done in https://github.com/SHY-Corp/LeetCode-Solutions/pull/308
