### ISSUE TITLE
923 | 3Sum With Multiplicity | C++

### ISSUE THREAD

**Issue by juhikushwah** [SHY-Corp/LeetCode-Solutions#1778]
## **`Title`** - Adding C++ code for 923. 3Sum With Multiplicity

**What will change** - Adding solution for leetcode problem 923

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by cmcgee0308** [comment]
Hi! If this issue isn't already assigned to anyone, I was wondering if I could get some more information about it?

**Comment by juhikushwah** [comment]
@cmcgee0308 Hi! This issue is already assigned, however, you can create your own issues. Make sure whatever issues you are creating, they are not already there in the repository. If you have a better solution, you can create issues accordingly.

Checkout the contributions guideline for more information: 
https://github.com/SHY-Corp/LeetCode-Solutions/blob/master/CONTRIBUTING.md
