### ISSUE TITLE
728 | Self Dividing Numbers | python

### ISSUE THREAD

**Issue by Mansi2814** [SHY-Corp/LeetCode-Solutions#178]
## **`Given a lower and upper number bound, output a list of every possible self dividing number, including the bounds if possible.`** -

**What will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by Mansi2814** [comment]
Please assign it to me.

**Comment by Aditya489** [comment]
can i also be assigned for this?
