### ISSUE TITLE
1260 | Shift 2D Grid | C++

### ISSUE THREAD

**Issue by juhikushwah** [SHY-Corp/LeetCode-Solutions#1783]
## **`Title`** - Adding C++ code for 1260. Shift 2D Grid

**What will change** - Adding solution for leetcode problem 1260

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by nurhaliza** [comment]
Please assign me this issue assignment.

**Comment by juhikushwah** [comment]
@nurhaliza Hi! This issue is already assigned. You can checkout the contributions guideline and create your own issues.
