### ISSUE TITLE
215 | Kth largest Element in an Array | Java

### ISSUE THREAD

**Issue by JOKUE2002** [SHY-Corp/LeetCode-Solutions#18]
## **`Challenge No. 215 - finding the Kth largest Element in an Array`** -

**What will change** -

The solution for the challenge 215 named "Kth Largest Element in an Array" will be provided.

### Type of Issue -

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

- [ ] Python
- [ ] C++
- [x] Java

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/Ftbj4a

Happy Coding,
JOKUE2002

**Comment by JOKUE2002** [comment]
I would love to take this one too.

**Comment by AryashDubey** [comment]
Hey Can I do this Please !?

**Comment by devesh-badal** [comment]
hey, i would love to solve this issue.

**Comment by SSKale1** [comment]
- [x] Assigned to @JOKUE2002 . On the basis of issue creation.

**Comment by SSKale1** [comment]
@AryashDubey  & @devesh-badal you can create issue for any other problem.
