### ISSUE TITLE
509 | Fibonacci Number | C++

### ISSUE THREAD

**Issue by juhikushwah** [SHY-Corp/LeetCode-Solutions#1800]
## **`Title`** - Adding C++ code for 509. Fibonacci Number

**What will change** - Adding solution for leetcode problem 509

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by kutlayacar** [comment]
I would like to work on this issue. Could you please assign me?

**Comment by juhikushwah** [comment]
@kutlayacar Hi! This is already assigned, however, you can checkout the contributions guideline and create your own issues. Will assign those to you.
