### ISSUE TITLE
387 | First Unique Character in a String | Python

### ISSUE THREAD

**Issue by jessicasalbert** [SHY-Corp/LeetCode-Solutions#181]
## 387 | First Unique Character in a String | Python #181

**What will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by jessicasalbert** [comment]
Would like to be assigned this one when you have a chance - thanks!

**Comment by Yashica7** [comment]
- [x] @jessicasalbert Assigned it to u

**Comment by Aditya489** [comment]
would like to be assigned this issue?

**Comment by ridhikapila27** [comment]
Kindly assign me this issue
