### ISSUE TITLE
23 | Merge k Sorted  | CPP

### ISSUE THREAD

**Issue by karan1808** [SHY-Corp/LeetCode-Solutions#182]
## **`Merge k Sorted`** -

**What will change** -

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by karan1808** [comment]
Please, can you assign me this issue? Thanks!

**Comment by Rohanfizz** [comment]
Hey can u please assign this to me?
Peace :)
