### ISSUE TITLE
Problem Number | Title | Language

### ISSUE THREAD

**Issue by mkn-root12** [SHY-Corp/LeetCode-Solutions#1834]
class Solution {
public:
    int poorPigs(int buckets, int minutesToDie, int minutesToTest) {
        return ceil(log(buckets) / log(minutesToTest / minutesToDie + 1));
    }
};

**Comment by mkn-root12** [comment]
Solution  for the leetcode hard problem -poor Pig

**Comment by juhikushwah** [comment]
> Solution for the leetcode hard problem -poor Pig

Hi! There is a guideline for submitting solutions. Please go through it and make PRs accordingly.
