### ISSUE TITLE
1854 | Maximum Population Year | C++

### ISSUE THREAD

**Issue by vipul-2003** [SHY-Corp/LeetCode-Solutions#1837]
## **`Title`** - 1854 Maximum population year leetcode Question 

hi there , 
I wanted to add solution for this problem [Maximum Population Year](https://leetcode.com/problems/maximum-population-year/) 
please assign this to me @juhikushwah 

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [ ] Python
- [x] C++
- [ ] Java
- [ ] SQL

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by soham2312** [comment]
Please assign this to me

**Comment by juhikushwah** [comment]
> Please assign this to me

Hi! This issue has already been assigned. You can create your own issue and ask me to assign it to you. Make sure the solution doesn't already exist in the code base.
