### ISSUE TITLE
1295 | Find Numbers with Even Number of Digits | C++

### ISSUE THREAD

**Issue by vipul-2003** [SHY-Corp/LeetCode-Solutions#1841]
## **`Title`** - Find Numbers with Even Number of Digits 

hi there , 
I wanted to add solution for this leetcode problem  [Find Numbers with Even Number of Digits](https://leetcode.com/problems/find-numbers-with-even-number-of-digits/)
please assign this to me @juhikushwah 

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [ ] Python
- [x] C++
- [ ] Java
- [ ] SQL

Happy Coding,

**Comment by juhikushwah** [comment]
@Abhishek-Verma75230 it was already assigned to someone. You can create your own issues and ask me to assign them to you.
