### ISSUE TITLE
5 | Longest Palindromic Substring | Java

### ISSUE THREAD

**Issue by HanningLin** [SHY-Corp/LeetCode-Solutions#186]
## **`5 | Longest Palindromic Substring | Java`** -

**What will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Java

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by HanningLin** [comment]
Please. Can you assign this issue to me?

**Comment by Rohanfizz** [comment]
Hey can u please assign this to me?
Peace :)
pleaseeeeeeeeee

**Comment by meghanagottapu** [comment]
can I work on this? @HanningLin

**Comment by Rohanfizz** [comment]
Thanks @Yashica7 for assigning this to me, will be making a pull request shortly.
Peace :)
