### ISSUE TITLE
89 | Gray Code | C++

### ISSUE THREAD

**Issue by gaurav1620** [SHY-Corp/LeetCode-Solutions#187]
## **`Title`** -
89. Gray Code
**What will change** -
A single file of the solution will be added in C++ folder.
### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [ ] Python
- [x] C++
- [ ] Java
- [ ] SQL

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by rebelfire888** [comment]
C++ code
