### ISSUE TITLE
139 | Word Break | C++

### ISSUE THREAD

**Issue by ricky1812** [SHY-Corp/LeetCode-Solutions#200]
## **`Title`** -

**What will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [ ] Python
- [x] C++
- [ ] Java
- [ ] SQL

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by ricky1812** [comment]
I want to work on this issue

**Comment by vrakr19** [comment]
@ricky1812 done with the problem. Can you assign this to me

**Comment by vrakr19** [comment]
@ricky1812 done with the pr. Can u check?

**Comment by SSKale1** [comment]
@ricky1812 cool down for a while. We'll let others contribute too.

**Comment by SSKale1** [comment]
- [x] Assigning to @vrakr19

**Comment by vrakr19** [comment]
@SSKale1 ok
