### ISSUE TITLE
169 | Majority Element | Python

### ISSUE THREAD

**Issue by JayeshSareen** [SHY-Corp/LeetCode-Solutions#203]
## **`Majority Element`** -

**What will change** -

### Type of Issue -

- Adding New Code

### Programming Language

-  Python

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by JayeshSareen** [comment]
Please assign me this issue @SSKale1

**Comment by Aditya489** [comment]
hi can i be assigned for this task?
