### ISSUE TITLE
367 | Valid Perfect Square | Python

### ISSUE THREAD

**Issue by JayeshSareen** [SHY-Corp/LeetCode-Solutions#204]
## **`Valid  Perfect Square`** -

**What will change** -

### Type of Issue -

-  Adding New Code

### Programming Language

-  Python

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by JayeshSareen** [comment]
Please assign it to me @SSKale1

**Comment by aryaniiit002** [comment]
> Please assign it to me @SSKale1

Can i work on this please?

**Comment by SSKale1** [comment]
- [x] Assigning to @JayeshSareen for issue creation.
