### ISSUE TITLE
1288| Remove Covered Intervals | C++

### ISSUE THREAD

**Issue by SHIVANATHRIHARIKRISHNA** [SHY-Corp/LeetCode-Solutions#208]
## **`Title`** -

**What will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.
- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by SHIVANATHRIHARIKRISHNA** [comment]
Please assign this to me.

**Comment by Yashica7** [comment]
- [x] @SHIVANATHRIHARIKRISHNA assigned it to you

**Comment by SHIVANATHRIHARIKRISHNA** [comment]
Thanks..

**Comment by SHIVANATHRIHARIKRISHNA** [comment]
This problem solution is already present in the repository.I haven't checked it beforehand..Can I submit it again..?Someone else have submitted this issue and solution into the repository already

**Comment by SSKale1** [comment]
@SHIVANATHRIHARIKRISHNA you can create another issue for some other problem.
