### ISSUE TITLE
32 | Longest Valid Parenthesis | C++

### ISSUE THREAD

**Issue by ricky1812** [SHY-Corp/LeetCode-Solutions#21]
## **`Title`** -

**What will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [ ] Python
- [x] C++
- [ ] Java

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/Ftbj4a

Happy Coding,

**Comment by ricky1812** [comment]
i want to work on it

**Comment by SSKale1** [comment]
- [x] Assigning to @ricky1812 .
