### ISSUE TITLE
229 | Majority Element II | Java

### ISSUE THREAD

**Issue by mrprince88** [SHY-Corp/LeetCode-Solutions#210]
## **`Title`** -

**What will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [ ] Python
- [ ] C++
- [x] Java
- [ ] SQL

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by taylor-abbas** [comment]
I am interested and would like to contribute to this. Could you please assign this problem to me?

**Comment by Yashica7** [comment]
Assigned it to @mrprince88 since he created the issue

**Comment by Yashica7** [comment]
@taylor-abbas You can create an issue and wait to get it assigned to you
