### ISSUE TITLE
215 | KthElementInAnArray | Java

### ISSUE THREAD

**Issue by SaimantikaBasu** [SHY-Corp/LeetCode-Solutions#217]
## **`Title`** -

**What will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Java

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by goodgodth** [comment]
Please assign this issue to me

**Comment by krishnmohan19** [comment]
hey @SaimantikaBasu .
Would you plz assign this to me in java/c++.

**Comment by SaimantikaBasu** [comment]
I have updated the code. Can you check that and let me know.
