### ISSUE TITLE
771 | Jewels and Stones | C++

### ISSUE THREAD

**Issue by amolgautam25** [SHY-Corp/LeetCode-Solutions#218]
## Jewels and Stones -

Adding new solution -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by kushaangowda** [comment]
Can you please assign this to me?

**Comment by amolgautam25** [comment]
please assign this problem to me . I am the issue creator.

**Comment by siddharthgangwar25** [comment]
Can i do this problem too, but in Python?

**Comment by Yashica7** [comment]
@amolgautam25 Assigned it to u

**Comment by Yashica7** [comment]
@siddharthgangwar25 You can create an issue for that

**Comment by amolgautam25** [comment]
Created a PR for this : https://github.com/SHY-Corp/LeetCode-Solutions/pull/345
