### ISSUE TITLE
128 | Longest Consecutive Sequence | C++

### ISSUE THREAD

**Issue by amolgautam25** [SHY-Corp/LeetCode-Solutions#221]
## Longest Consecutive Sequence

Adding new code for Longest Consecutive Sequence in C++

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Cod

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by guptag911** [comment]
I want to work on this problem.Please assign it to me.

**Comment by amolgautam25** [comment]
please assign this problem to me . I am the issue creator.

**Comment by amolgautam25** [comment]
I have created a PR for this : https://github.com/SHY-Corp/LeetCode-Solutions/pull/343
