### ISSUE TITLE
27 | RemoveElement | Java

### ISSUE THREAD

**Issue by SaimantikaBasu** [SHY-Corp/LeetCode-Solutions#225]
## **`RemoveElement`** -

**What will change** - New and easier code

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Java

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by richnavska** [comment]
Hello, I´m interesting in this issue and I would like to contribute this. Thank you!

**Comment by theroyalraj** [comment]
Hi, I want to work on this issue. Please assign it to me.

**Comment by SSKale1** [comment]
PR Merged.

**Comment by richnavska** [comment]
Hello,
I have subject in university and we should create some units tests. So I want to ask you if I can create some units test for this project.  Thank you. @SSKale1 @Yashica7

**Comment by SSKale1** [comment]
Exactly what unit tests are you thinking? @richnavska

**Comment by richnavska** [comment]
Input and output tests. @SSKale1
