### ISSUE TITLE
67 | Add Binary | C++

### ISSUE THREAD

**Issue by MrAman007** [SHY-Corp/LeetCode-Solutions#226]
## **`67 | Add binary problem in C++`** -

**What will change** -

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by MrAman007** [comment]
assign me to this problem, thanks

**Comment by Aditya489** [comment]
hi can i be assigned for this task? thank you!

**Comment by Yashica7** [comment]
Assigned @MrAman007

**Comment by Yashica7** [comment]
@Aditya489 You can create an Issue to contribute
