### ISSUE TITLE
1 | Two Sum | C++

### ISSUE THREAD

**Issue by MrAman007** [SHY-Corp/LeetCode-Solutions#232]
## **`1 | Two Sum Problem in C++`** 

**What will change** -

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] C++

**Comment by aryaniiit002** [comment]
Can you assign this to me @aryaniiit002 ?

**Comment by MrAman007** [comment]
assign me to this problem please, thankyou

**Comment by shresth12-jain** [comment]
Hi,

I would like to contribute to this, I solved it very simply in LeetCode. Kindly allow me to solve this issue.

Thanks & Regards
Shresth Jain

**Comment by SHIVANATHRIHARIKRISHNA** [comment]
@shresth12-jain If you want to solve some problem,create your own issue on the problems of leetcode which are not present in this repository and ask the maintainers to assign it to you.

**Comment by Aman23092001** [comment]
I have solve quite a good amount of questions on leetcode and that too with cpp. So I think this I can do very easily.
So, I will request you to assign this problem to me.

**Comment by Yashica7** [comment]
@shresth12-jain @Aman23092001 Create an issue to contribute
