### ISSUE TITLE
118. | Pascal's Triangle | Python

### ISSUE THREAD

**Issue by tzvog** [SHY-Corp/LeetCode-Solutions#237]
## **`Title`** - Pascal's Triangle

**What will change** -
i will create a new file to solve this problem 

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by tzvog** [comment]
please assign this to me

**Comment by Aviadonis** [comment]
Can I please work on this? Thanks in advance 🙌

**Comment by jayaganeshkumar** [comment]
@tzvog  please assign this to me.

**Comment by tzvog** [comment]
Hey @jayaganeshkumar  and @Aviadonis !
I'm not in charge of the complete repository and cannot assign Issues to people (I'm currently asking to be assigned).
I would suggest finding problems on LeetCode that have not already been done or have issues regarding it create your own issue and ask to be assigned.

**Comment by jayaganeshkumar** [comment]
@tzvog  thank you sir
