### ISSUE TITLE
189 | Rotate Array | C++

### ISSUE THREAD

**Issue by shruti1421** [SHY-Corp/LeetCode-Solutions#239]
## **`Title`** - 189.  Rotate Array

**What will change** -

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by shruti1421** [comment]
Please assign this to me.

**Comment by riyabhatia26** [comment]
Could you please assign this to me?
