### ISSUE TITLE
626 | Exchange Seats | SQL

### ISSUE THREAD

**Issue by JOKUE2002** [SHY-Corp/LeetCode-Solutions#24]
## **`Add some Databases to the mix`** - Challenge 626

**What will change** - The challenge no. 626 from the Databases category will be added

### Type of Issue

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

- [ ] Python
- [ ] C++
- [ ] Java
- [x] MySQL

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/Ftbj4a

Happy Coding,
JOKUE2002

**Comment by JOKUE2002** [comment]
I would love to make the start with this SQL-Challenge.

**Comment by SSKale1** [comment]
Good Going @JOKUE2002 .
- [x] Assigning to @JOKUE2002

**Comment by SSKale1** [comment]
@JOKUE2002  Just Make Sure you make a new directory.

**Comment by JOKUE2002** [comment]
Sure 👍
