### ISSUE TITLE
75| Sort Colors| C++

### ISSUE THREAD

**Issue by shresth12-jain** [SHY-Corp/LeetCode-Solutions#245]
## **`Title`** -

**What will change** -

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] C++

Happy Coding,

**Comment by shresth12-jain** [comment]
Hi,

I would like to contribute to this, I solved it very simply in LeetCode. Kindly allow me to solve this issue.

Thanks & Regards
Shresth Jain

**Comment by Yashica7** [comment]
@shresth12-jain Assigned it to you for now, wait to get it assigned before you make a pull request next time, it'll help us in reviewing

**Comment by shresth12-jain** [comment]
@Yashica7 thanks for assigning me this issue, yes I will take it as a note from now onwards. Kindly review my request & let me know if any modification required.
