### ISSUE TITLE
704 | BINARY SEARCH | CPP

### ISSUE THREAD

**Issue by Aman23092001** [SHY-Corp/LeetCode-Solutions#248]
## **`704 | BINARY SEARCH | C++`** -

**What will change** -

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by Aman23092001** [comment]
Hi, I have a solve quite a lot problems on LeetCode and that too with C++. This problem is very famous on LeetCode.
Please assign it to me. I can solve it very easily.
Thank You!!!

**Comment by Yashica7** [comment]
- [x] Assigned it to u @Aman23092001

**Comment by ritish1912** [comment]
I have been practicing a lot of these kind of problems on different programming platforms . Please assign it to me. I am really really  willing to do it
