### ISSUE TITLE
1108 | Defanging an IP Address | C++

### ISSUE THREAD

**Issue by jatinAgarwala** [SHY-Corp/LeetCode-Solutions#249]
## **`Title`** - Adding solution for problem Defanging an IP Address (https://leetcode.com/problems/defanging-an-ip-address/)

**What will change** - A solution code will be added for the problem

### Type of Issue - Adding new code for a problem

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by jatinAgarwala** [comment]
Please assign this to me.

**Comment by Yashica7** [comment]
Assigned @jatinAgarwala
