### ISSUE TITLE
1051 | Height Checker | C++

### ISSUE THREAD

**Issue by Yashica7** [SHY-Corp/LeetCode-Solutions#25]
## **`Title`** -

**1051. Height Checker** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- [x] Ask for issue assignment before making Pull Request.
- [x] Add your file in the proper folder
- [x] Clean Code` and `Documentation` for better readability
- [x] Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/Ftbj4a

**Comment by VishalAmbavade** [comment]
Hi @Yashica7 , I would like to wok on this issue.

**Comment by VishalAmbavade** [comment]
Here's the link to the code: https://github.com/VishalAmbavade/Hacktoberfest/blob/main/heightChecker.cpp

**Comment by aditsawant** [comment]
@Yashica7 hey there,
I would like to be assigned to this issue :)
Thanks!

**Comment by SSKale1** [comment]
PR Merged closing issue.
