### ISSUE TITLE
41 | First Missing Positive | Java

### ISSUE THREAD

**Issue by HanningLin** [SHY-Corp/LeetCode-Solutions#257]
## **`41 | First Missing Positive | Java`** -

**What will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [ ] Python
- [ ] C++
- [x] Java
- [ ] SQL

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by HanningLin** [comment]
Can you assign this to me?

**Comment by HanningLin** [comment]
Can you assign this to me?

**Comment by akshaykumarrai** [comment]
hey, would like to start first pr with this question .Can u please assign it to me?

**Comment by HanningLin** [comment]
> hey, would like to start first pr with this question .Can u please assign it to me?

It's very easy to create a new issue. Feel free to create one and solve it.
