### ISSUE TITLE
72 | Edit Distance | C++

### ISSUE THREAD

**Issue by ricky1812** [SHY-Corp/LeetCode-Solutions#26]
## **`Title`** -

**What will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Code
- [x] Improving Documentation
- [x] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/Ftbj4a

Happy Coding,

**Comment by ricky1812** [comment]
I want to work on it.

**Comment by AryashDubey** [comment]
Hey Can I work On it

**Comment by nayanika0208** [comment]
hey Can i work on this issue??

**Comment by Yashica7** [comment]
- [x] Assigned to @ricky1812

**Comment by VIPUL662** [comment]
i can solve this please assign it to me.
