### ISSUE TITLE
46 | Permutations | C#

### ISSUE THREAD

**Issue by Danotsonof** [SHY-Corp/LeetCode-Solutions#261]
## **`Permutations`**

**What will change**

### Type of Issue

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C#

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by Danotsonof** [comment]
Could you assign this to me? Thanks

**Comment by SSKale1** [comment]
We do not currently have a Codebase for C#. You can try for an issue in c++, java or python currently.
