### ISSUE TITLE
136 | Single Number | Python

### ISSUE THREAD

**Issue by Jitesh111** [SHY-Corp/LeetCode-Solutions#277]
### Type of Issue -

- Adding New Code

### Programming Language

- Python

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by Jitesh111** [comment]
Assign me this issue. Thanks

**Comment by Largetable** [comment]
I'd like to be assigned to this one please.

**Comment by Jitesh111** [comment]
Can you please tell me why I was not assigned this issue @Yashica7
