### ISSUE TITLE
287 | Find the Duplicate Number | Python

### ISSUE THREAD

**Issue by Jitesh111** [SHY-Corp/LeetCode-Solutions#279]
### Type of Issue 

-  Adding New Code

### Programming Language

-  Python

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by Jitesh111** [comment]
Please assign me this. Thanks

**Comment by harshitalashkari** [comment]
please assign me this.

**Comment by chehak123** [comment]
please assign to me

**Comment by Largetable** [comment]
I'd like to get assigned to this!
