### ISSUE TITLE
4 | Median of Two Sorted Arrays | Java

### ISSUE THREAD

**Issue by dsibilio** [SHY-Corp/LeetCode-Solutions#28]
## **`4 | Median of Two Sorted Arrays | Java`** -

**What will change** -

Add Java solution to the LeetCode problem: **4. Median of Two Sorted Arrays**

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [ ] Python
- [ ] C++
- [x] Java

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/Ftbj4a

Happy Coding,

**Comment by Pradyuman7** [comment]
I can work on this issue. @dsibilio would it be possible to assign this to me?

**Comment by dsibilio** [comment]
This issue should already be solved by PR #30 
You can go ahead and create clones of this issue for a different programming language 👍

**Comment by aditsawant** [comment]
Hey @dsibilio, I'd love to help.
Can you please assign this issue to me?
Thanks

**Comment by SSKale1** [comment]
- [x] Assigning to @dsibilio
