### ISSUE TITLE
1395 | Count number of teams | Java

### ISSUE THREAD

**Issue by JOKUE2002** [SHY-Corp/LeetCode-Solutions#281]
## **`Challenge no. 1395: Count number of teams (medium)`** -

**What will change** 
The solution for challenge 1395 will be added

### Type of Issue

- [x] Adding New Code

### Programming Language

- [x] Java

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding.

**Comment by JOKUE2002** [comment]
Would love to take this.

**Comment by TusharSharmaIN** [comment]
Can you please assign it to me.
