### ISSUE TITLE
7 | Reverse Integer | C++

### ISSUE THREAD

**Issue by hjpassion** [SHY-Corp/LeetCode-Solutions#282]
## **`Title`** -

**What will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Code
- [x] Improving Documentation
- [x] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [ ] Python
- [x] C++
- [ ] Java
- [ ] SQL

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by hjpassion** [comment]
please assign this topic to me @SSKale1

**Comment by TusharSharmaIN** [comment]
please assign this to me.

**Comment by chehak123** [comment]
please assign to me

**Comment by PODU** [comment]
I would like to work on this.

**Comment by chehak123** [comment]
I want to work on this issue

**Comment by minks21** [comment]
Will try to provide with the best optimize code. Can you please assign this to me

**Comment by SSKale1** [comment]
- [x] Assigning to @hjpassion for issue creation.
