### ISSUE TITLE
169 | Majority Element | C++

### ISSUE THREAD

**Issue by shruti1421** [SHY-Corp/LeetCode-Solutions#285]
## **`Title`** - Majority Element

**What will change** -

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by shruti1421** [comment]
Please assign this problem to me.

**Comment by chehak123** [comment]
please assign this to me

**Comment by ashima0699** [comment]
please assign this to me

**Comment by ritish1912** [comment]
please assign this to me.
i am willing to do this problem

**Comment by rohanmahto592** [comment]
please assign this to me

**Comment by SSKale1** [comment]
- [x] Assigning to @shruti1421

**Comment by SSKale1** [comment]
@shruti1421 you plan on implementing this?

**Comment by shruti1421** [comment]
Sorry for doing it late.
