### ISSUE TITLE
2. | Add Two NumbersProblem Number | Python

### ISSUE THREAD

**Issue by OMEGAeNcore** [SHY-Corp/LeetCode-Solutions#286]
### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] Python

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by OMEGAeNcore** [comment]
Please assign me to this. Thank you.

**Comment by chehak123** [comment]
please assign to me

**Comment by priyalgupta09** [comment]
hey! please assign this to me

**Comment by Largetable** [comment]
I'd like to be assigned to this!
