### ISSUE TITLE
Can I Add Multiple Problems

### ISSUE THREAD

**Issue by Siddhant-K-code** [SHY-Corp/LeetCode-Solutions#289]
Can I Add Following Problem's Solution in C++:

* 1311 Get Watched Videos By Your Friends
* 546 Remove Boxes
* 507 Perfect Number
* 12 Integer To Roman
* 11 Container With Most Water
* 10 Regular Expression Matching
* 8 String To Integer
* 7 Reverse Integer
* 6 ZigZag Conversion
* 2 Add Two Numbers

**Comment by SSKale1** [comment]
You'll have to add a single problem per issue for now. Also make sure you check for already existing problems.

**Comment by Siddhant-K-code** [comment]
OK
