### ISSUE TITLE
42 | Trapping rain water | Java

### ISSUE THREAD

**Issue by Pradyuman7** [SHY-Corp/LeetCode-Solutions#31]
## **`Trapping rain water`** -

**What will change** -
Java code for problem 42 Trapping rain water will be added.

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [ ] Python
- [ ] C++
- [x] Java

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/Ftbj4a

Happy Coding,

**Comment by Pradyuman7** [comment]
@SSKale1 would it be possible to assign this issue to me?

**Comment by aditsawant** [comment]
@SSKale1 @Yashica7 
I would love to help. Can you please assign this issue to me? 
Thanks!

**Comment by SSKale1** [comment]
- [x] Assigning to @Pradyuman7 for issue creation.

**Comment by SSKale1** [comment]
@aditsawant You can make any other issue.
