### ISSUE TITLE
1310 |  XOR Queries of a Subarray | C++

### ISSUE THREAD

**Issue by Rohanfizz** [SHY-Corp/LeetCode-Solutions#312]
## **`1310 | XOR Queries of a Subarray | C++`** -

**What will change** - Solution for the problem 1310. XOR Queries of a Subarray  will be added to C++ folder

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by Rohanfizz** [comment]
Hope you are having a good day, Please Assign this issue to me :)
Peace :)

**Comment by Yashica7** [comment]
- [x] Assigned it to u @Rohanfizz

**Comment by Rohanfizz** [comment]
@Yashica7 , issue resolved, please check #328 .
Thanks :)
