### ISSUE TITLE
730 | Count Different Palindromic Subsequences | C++

### ISSUE THREAD

**Issue by IliasKhan** [SHY-Corp/LeetCode-Solutions#321]
## **`Title`** - **Count Different Palindromic Subsequences**

**What will change** -  
 Solution for the problem 730. Count Different Palindromic Subsequences will be added in C++

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by IliasKhan** [comment]
Hi, Please assign this to me.

**Comment by SriCoD** [comment]
could i be assigned this

**Comment by Yashica7** [comment]
- [x]  Assigned it to u @IliasKhan
