### ISSUE TITLE
13| Roman To Integer | C++

### ISSUE THREAD

**Issue by hjpassion** [SHY-Corp/LeetCode-Solutions#323]
## **`Title`** -

**What will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Code
- [x] Improving Documentation
- [x] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [ ] Python
- [x] C++
- [ ] Java
- [ ] SQL

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by hjpassion** [comment]
please assign me this issue @SSKale1 @Yashica7

**Comment by SriCoD** [comment]
i can do this very well ,would love to work on it @hjpassion

**Comment by geekaditi** [comment]
I would like to take this up in CPP. Please assign it to me.

**Comment by Infinityz** [comment]
I would like to work on this in Java if that's alright!
