### ISSUE TITLE
933 | Number of Recent Calls | 933

### ISSUE THREAD

**Issue by DarkWarrior703** [SHY-Corp/LeetCode-Solutions#33]
### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.
- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/Ftbj4a

Happy Coding,

**Comment by VishalAmbavade** [comment]
Hi @DarkWarrior703, I'm interested to work on this issue.

**Comment by VishalAmbavade** [comment]
Here's the link to the code: https://github.com/VishalAmbavade/Hacktoberfest/blob/main/recentCalls.cpp

**Comment by Yashica7** [comment]
@DarkWarrior703 I have assigned you for now but please wait to get assigned next time before you make a pull request, it'll help us in reviewing

**Comment by SSKale1** [comment]
- [x] Assigning to @VishalAmbavade

**Comment by SSKale1** [comment]
@VishalAmbavade Do you plan to implement this?

**Comment by Yashica7** [comment]
We'll be closing this issue now as it has been 20 days and there is no response, you can create an issue again if you wish to work on it @VishalAmbavade
