### ISSUE TITLE
224 | Basic Calculator | Java

### ISSUE THREAD

**Issue by HanningLin** [SHY-Corp/LeetCode-Solutions#347]
## **`224 | Basic Calculator | Java`** -

**What will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Java

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by HanningLin** [comment]
I am trying to complete my Hacktoberfest. Can you assign this issue to me pleaseeeeeee!

**Comment by deepharshsri** [comment]
Hey, can you assign me to this task?
