### ISSUE TITLE
421 | Maximum XOR of Two Numbers in an Array | Java

### ISSUE THREAD

**Issue by SharmaRajesh007** [SHY-Corp/LeetCode-Solutions#350]
## **`421 | Maximum XOR of Two Numbers in an Array | Java`** -

**What will change** - add solution for 421 Maximum XOR of Two Numbers in an Array Java

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by SharmaRajesh007** [comment]
Please assign this issue to me.
Regards

**Comment by rmrn65** [comment]
Can I work on this. I want to solve this using java.

**Comment by SharmaRajesh007** [comment]
Issue solved, Please review. @Yashica7 
Peace :)
