### ISSUE TITLE
88 | Merge Sorted Array | Python

### ISSUE THREAD

**Issue by j3r3mias** [SHY-Corp/LeetCode-Solutions#358]
## **`Merge Sorted Array`** -

Solution to the problem 88 (Merge Sorted Array).

### Type of Issue -

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

- [x] Python
- [ ] C++
- [ ] Java
- [ ] SQL

**Comment by SSKale1** [comment]
@j3r3mias I'm assigning you this issue now but in the future make sure, you wait to be assigned to any issue, before making a PR.
