### ISSUE TITLE
905 | Sort Array by Parity | C++

### ISSUE THREAD

**Issue by Yashica7** [SHY-Corp/LeetCode-Solutions#364]
### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by dhanika08** [comment]
I can work on this issue , please assign this to me

**Comment by Yashica7** [comment]
@dhanika08 This has already been assigned,you can create an Issue and wait for it to be assigned
