### ISSUE TITLE
101 | Symmetric Tree| C++

### ISSUE THREAD

**Issue by Aman23092001** [SHY-Corp/LeetCode-Solutions#378]
## **`Symmetric Tree`** -

**What will change** -

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by lashewi** [comment]
Can I work on this?

**Comment by Aman23092001** [comment]
Hey, I want to work on this.
Thank you!!!

**Comment by HansaHalim** [comment]
I want to work on this! Please assign me!
