### ISSUE TITLE
326 | Power of Three | C++

### ISSUE THREAD

**Issue by devesh-badal** [SHY-Corp/LeetCode-Solutions#38]
## **`Title`** - challenge no. 326 - Power of Three

**What will change** - The solution for the problem will be provided.

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [ ] Python
- [x] C++
- [ ] Java

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/Ftbj4a

Happy Coding,

**Comment by PrathamesR** [comment]
I can solve this problem, can I be assigned to do it?

**Comment by devesh-badal** [comment]
@SSKale1 I would like to work on this issue.

**Comment by Yashica7** [comment]
- [x] Assigned to @devesh-badal
