### ISSUE TITLE
199 | Binary Tree Right Side View | C++

### ISSUE THREAD

**Issue by HansaHalim** [SHY-Corp/LeetCode-Solutions#381]
## **`Binary Tree Right Side View`** -

**What will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by HansaHalim** [comment]
Please assign me to this issue! I want to work on it!

**Comment by pawki07** [comment]
Hey, I would like to contribute to this issue. Please assign it to me.
