### ISSUE TITLE
152 | Maximum Product Subarray | C++

### ISSUE THREAD

**Issue by smitgajjar** [SHY-Corp/LeetCode-Solutions#382]
## **`Maximum Product Subarray`** -

**What will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by smitgajjar** [comment]
I want to work on this.
Can you assign it to me?
Thank you...

**Comment by ITES7321** [comment]
#386 Have added the answer :) Thank You!
