### ISSUE TITLE
151 | Reverse Words in a String | C++

### ISSUE THREAD

**Issue by Sinha199** [SHY-Corp/LeetCode-Solutions#383]
## **Reverse Words in a String** -

**What will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [ ] Python
- [x] C++
- [ ] Java
- [ ] SQL

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by Tahreem-Khalil** [comment]
hello, how are you?
I want to be assigned to this issue.
Thank you.

**Comment by Isha2208** [comment]
Hey, **@Sinha199** can you assign it to me. Will like to contribute.

**Comment by jainsarthak216** [comment]
Please assign this to me.

**Comment by Isha2208** [comment]
Hey, @Sinha199 can i be assigned for this issue. Will like to contribute.

**Comment by SSKale1** [comment]
@Tahreem-Khalil you can create your own issue.

**Comment by Ruchi101** [comment]
Hey, @Sinha199 can you assign it to me. Would like to contribute. Thanks
