### ISSUE TITLE
1431 | Kids With the Greatest Number of Candies| C++

### ISSUE THREAD

**Issue by ITES7321** [SHY-Corp/LeetCode-Solutions#387]
## **`Kids With the Greatest Number of Candies`** -

**What will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by ITES7321** [comment]
Can I work on this problem?Thanks!

**Comment by Sindhu-321** [comment]
Can I get this assigned? Thanks

**Comment by ary1733** [comment]
Please assign this to me, thank you.

**Comment by aveni121** [comment]
Can I work on this problem please?

**Comment by nk183** [comment]
Can I work on this problem please?

**Comment by xcyraxx** [comment]
hey can i work on this? thanks
