### ISSUE TITLE
1288 | Remove Covered Intervals | C++

### ISSUE THREAD

**Issue by aditsawant** [SHY-Corp/LeetCode-Solutions#39]
## **`Title`** - Problem No. 1288 | Leetcode | C++

**What will change** -
A properly commented and efficient solution will be added to the aforementioned problem.

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [ ] Python
- [x] C++
- [ ] Java

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/Ftbj4a

Happy Coding,

**Comment by aditsawant** [comment]
Please assign it to me

**Comment by SSKale1** [comment]
- [x] Assigning to @aditsawant .
