### ISSUE TITLE
338 | Counting Bits | Python

### ISSUE THREAD

**Issue by Melvin-Abraham** [SHY-Corp/LeetCode-Solutions#390]
## **`Title`** - Counting Bits

**What will change** - Addition of solution for _338. Counting Bits_ in Python

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [x] Python
- [ ] C++
- [ ] Java
- [ ] SQL

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife: Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by Melvin-Abraham** [comment]
Please assign me this issue...

**Comment by Ruchi101** [comment]
Please assign this task to me.

**Comment by liamm91** [comment]
Can you assign me this issue?
