### ISSUE TITLE
1480 | Running Sum of 1d Array | Python

### ISSUE THREAD

**Issue by lashewi** [SHY-Corp/LeetCode-Solutions#408]
## **`Title - Running Sum of 1d Array`** 

**What will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [x] Python
- [ ] C++
- [ ] Java
- [ ] SQL

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by parkerqueen** [comment]
Hey, I would love to work on this issue.

**Comment by Divyansh833** [comment]
Hey @lashewi , I am Searching for my very first Hacktoberfest and this looks very perfect for me.
Could you please assign it to me.
Thanks in advance :) !!
