### ISSUE TITLE
1029 | Two City Scheduling | Java

### ISSUE THREAD

**Issue by Khushaliketan** [SHY-Corp/LeetCode-Solutions#409]
## **`Title`** - Two City Scheduling

**What will change** - New Java code that beats 100% time complexity distribution of all submissions.

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [ ] Python
- [ ] C++
- [x] Java
- [ ] SQL

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by Khushaliketan** [comment]
Hi, I am proposing a Java solution that beats 100% time complexity distribution of all submissions on Leetcode. Would love to commit a PR if assigned!

**Comment by Chidu2000** [comment]
I would like to contribute here, please assign me

**Comment by Bhaswati-Saha** [comment]
would like to contribute. Please assign it to me.

**Comment by dougnobrega** [comment]
Hello, I would like to contribute too. Please assign it to me (:
I solve in C++, now I will write the code in java
Runtime: 0 ms, faster than 100.00% of C++ online submissions for Two City Scheduling.

**Comment by dougnobrega** [comment]
I got it (:
Runtime: 0 ms, faster than 100.00% of Java online submissions for Two City Scheduling.

**Comment by AaronF3PS** [comment]
I would like to contribute feel free to assign me this task
