### ISSUE TITLE
19 | Remove Nth Node From End Of List | Java

### ISSUE THREAD

**Issue by Khushaliketan** [SHY-Corp/LeetCode-Solutions#410]
## **`Title`** - Remove Nth Node From End Of List

**What will change** - New Java code will be added

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [ ] Python
- [ ] C++
- [x] Java
- [ ] SQL

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by rathovarun** [comment]
@Khushaliketan Can you assign this to me? thank you!

**Comment by IsuruAriyarathne** [comment]
Can you assign this to me

**Comment by Khushaliketan** [comment]
@rathovarun @IsuruAriyarathne I don't have write access in this repo. Besides, I am waiting for the maintainer to assign myself. Good luck! :)

**Comment by Khushaliketan** [comment]
@SSKale1 request to merge the pull request and add hacktoberfest-accepted tag, thanks!

**Comment by sb19** [comment]
please assign this task to me.
