### ISSUE TITLE
1208 | Get Equal Substrings Within Budget | Java

### ISSUE THREAD

**Issue by Khushaliketan** [SHY-Corp/LeetCode-Solutions#411]
## **`Title`** - Get Equal Substrings Within Budget

**What will change** - New Java code will be added under appropriate folder.

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [ ] Python
- [ ] C++
- [x] Java
- [ ] SQL

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by Khushaliketan** [comment]
Hi, I am proposing a Java solution to this question using the **Sliding Window** technique. Would love to commit a PR!

**Comment by ciso112** [comment]
Can you assign this to me? :)

**Comment by 19isha98** [comment]
Hey I am interested in doing it could you please assign it to me. And can I submit in Java?

**Comment by gunjan1831** [comment]
hey, can i offer a C++ solution?

**Comment by Khushaliketan** [comment]
@SSKale1 request to merge the **assigned pull request** and add hacktoberfest-accepted tag, thanks!
