### ISSUE TITLE
797 | All Paths From Source To Target | Java

### ISSUE THREAD

**Issue by Khushaliketan** [SHY-Corp/LeetCode-Solutions#413]
## **`Title`** - All Paths From Source To Target

**What will change** - New optimised Java code that beats 95.78% Time Distribution of all submissions.

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [ ] Python
- [ ] C++
- [x] Java
- [ ] SQL

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by harshitalashkari** [comment]
Can you please assign this to me? I 'll use java

**Comment by Khushaliketan** [comment]
@SSKale1  request to merge the pull request and add hacktoberfest-accepted tag, thanks!
