### ISSUE TITLE
26 | Remove Duplicates from Sorted Array | Python

### ISSUE THREAD

**Issue by devanshkaria88** [SHY-Corp/LeetCode-Solutions#419]
## **`Remove Duplicates from Sorted Array`** -

**What will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [x] Python
- [ ] C++
- [ ] Java
- [ ] SQL

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by devanshkaria88** [comment]
please assign me this issue @Yashica7 @SSKale1

Thx !!

**Comment by ShubhamNagure** [comment]
Hi @devanshkaria88 
I can do it.
Please assign me.

**Comment by liamm91** [comment]
Can you assign this issue to me?

**Comment by malaika2820** [comment]
Can you assign this issue to me? Thanks!

**Comment by pawki07** [comment]
Hey, I would like to work on this issue. Please assign it to me.
