### ISSUE TITLE
1050 | PrimeFactors | Java

### ISSUE THREAD

**Issue by colmanfranco** [SHY-Corp/LeetCode-Solutions#420]
## **`PrimeFactors `** -

**What will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [] Improving Code
- [] Improving Documentation
- [] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [] Python
- [] C++
- [x] Java
- [] SQL

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by colmanfranco** [comment]
would like to add this problem. Please assign it to me

**Comment by Kartik1745** [comment]
I would like to contribute, can I be assigned to work on this issue?

**Comment by rachita19082** [comment]
I would like to contribute to this issue. Could I please be assigned to it?

**Comment by Bhaswati-Saha** [comment]
Would like to contribute. Can you please assign it to me?
