### ISSUE TITLE
4 | Median of Two Sorted Arrays | Python

### ISSUE THREAD

**Issue by UdeshAthukorala** [SHY-Corp/LeetCode-Solutions#435]
## **`Median of Two Sorted Arrays`** -

**What will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [x] Python
- [ ] C++
- [ ] Java
- [ ] SQL

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by UdeshAthukorala** [comment]
@Yashica7 @SSKale1 Hey, I'd like to work on this problem. Can you please assign it to me?

**Comment by ambuj2000** [comment]
Please assign me this issue

**Comment by liamm91** [comment]
Can you assign me this issue?

**Comment by msmaitran** [comment]
I'd like to work on this issue.

**Comment by aryanmanchanda** [comment]
can you assign me?
