### ISSUE TITLE
23 | Merge k Sorted Lists | Java

### ISSUE THREAD

**Issue by Pradyuman7** [SHY-Corp/LeetCode-Solutions#44]
## **`Merge k Sorted Lists`** -

**What will change** -
Solution to problem 23 Merge k Sorted Lists will be added.

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [ ] Python
- [ ] C++
- [x] Java

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/Ftbj4a

Happy Coding,

**Comment by Pradyuman7** [comment]
@Yashica7 could you please assign this issue to me?

**Comment by Abhi-thecoder** [comment]
Please Assign it to me

**Comment by Yashica7** [comment]
- [x]  @Pradyuman7 Assigned it to you since you have made this Issue

**Comment by Yashica7** [comment]
@Abhi-thecoder Hi, you can create some other Issue since this has been assigned to someone else, thanks

**Comment by Abhi-thecoder** [comment]
Sorry, I will take care from next time.
