### ISSUE TITLE
74 | Search a 2D Matrix | C++

### ISSUE THREAD

**Issue by arpit7714** [SHY-Corp/LeetCode-Solutions#445]
## **`Title`** - Search a 2D Matrix

**What will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [ ] Python
- [x] C++
- [ ] Java
- [ ] SQL

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by arpit7714** [comment]
Please assign this to me

**Comment by kakabisht** [comment]
Hi, i could take this issue up let me know if it is up for grabs.

**Comment by snehaa1989** [comment]
please assign this to me..

**Comment by Tejas-Gosavi** [comment]
will you plz assign this task to me!!!
