### ISSUE TITLE
701 | Insert into a Binary Search Tree | C++

### ISSUE THREAD

**Issue by aditsawant** [SHY-Corp/LeetCode-Solutions#45]
## **`Title`** - 701 | Insert into a Binary Search Tree | C++

**What will change** -
Adding a solution to this Leetcode problem.
### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [ ] Python
- [x] C++
- [ ] Java
- [ ] SQL

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by aditsawant** [comment]
Please assign it to me

**Comment by Yashica7** [comment]
- [x] @aditsawant Assigned
