### ISSUE TITLE
704 | BinarySearch| c++

### ISSUE THREAD

**Issue by AbdulSameer47** [SHY-Corp/LeetCode-Solutions#450]
## **`BinarySearch`** -

**added the main class, header file and the given vector will be sorted before search because in binary search its important that the given elements are in sorted order ** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

**Comment by Pratyushraj2121** [comment]
Please assign this to me! I can do this!

**Comment by AniketDGiri** [comment]
Could you please assign this to me?
