### ISSUE TITLE
220 | Contains Duplicate III | C++

### ISSUE THREAD

**Issue by Darsh4521** [SHY-Corp/LeetCode-Solutions#455]
## **`Contains Duplicate III`** -

**What will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [] Improving Code
- [] Improving Documentation
- [] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [] Python
- [x] C++
- [] Java
- [] SQL

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by Darsh4521** [comment]
Assign this issue to me  please.

**Comment by isrivastav99** [comment]
Can you assign this to me for the C++ code?
