### ISSUE TITLE
78 | Subsets of a given array | C++

### ISSUE THREAD

**Issue by gitarthasarma** [SHY-Corp/LeetCode-Solutions#457]
## **`Subsets of a given array(no duplicates) `** -

**What will change** -

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by muskanvk** [comment]
please assign it to me !

**Comment by gitarthasarma** [comment]
I have the changes, can assign to me.
