### ISSUE TITLE
41 | First Missing Positive | C++

### ISSUE THREAD

**Issue by aditsawant** [SHY-Corp/LeetCode-Solutions#46]
## **`Title`** - 41 | First Missing Positive | C++

**What will change** -
Adding a solution to this problem.

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [ ] Python
- [x] C++
- [ ] Java
- [ ] SQL

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by aditsawant** [comment]
Please assign it to me.

**Comment by hjpassion** [comment]
please assign some tasks to me

**Comment by Yashica7** [comment]
@aditsawant Assigned it to you, make sure only this code is committed in the pull request, Thanks

**Comment by Yashica7** [comment]
@hjpassion Sure, make an Issue for whichever Leetcode Solution you'd like to contribute and see to it that no one else has done it

**Comment by chehak123** [comment]
Please assign to me also
