### ISSUE TITLE
52 | N-Queens II | Java

### ISSUE THREAD

**Issue by jntushar** [SHY-Corp/LeetCode-Solutions#470]
## **`Title`** - 52 | N-Queens II | Java

**What will change** - Adding solution to problem 52

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [ ] Python
- [ ] C++
- [x] Java
- [ ] SQL

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by jntushar** [comment]
Please assign this issue to me

**Comment by ChetanaL09** [comment]
Please assign this to me for Python.

**Comment by jntushar** [comment]
Hi @ChetanaL09 
It's good to see that you want to contribute but read the contributing.md file first
you should open your own issues and then ask for assign
This issue is already assigned to me and i have already opened pull request.
