### ISSUE TITLE
200 | Number Of Islands | C++

### ISSUE THREAD

**Issue by geetanshatrey** [SHY-Corp/LeetCode-Solutions#474]
## **`Title`** - Number Of Islands

**What will change** - Adding a new file that is Q 200. Number Of Islands on LeetCode in C++. 

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [] Improving Code
- [] Improving Documentation
- [] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [] Python
- [x] C++
- [] Java
- [] SQL

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by RachanaKampli** [comment]
hey @geetanshatrey can you assign this to me?

**Comment by madhavmalik16** [comment]
Hey @geetanshatrey can you assign this issue to me?

**Comment by Rajeet10** [comment]
plz assign me it will be a good help

**Comment by ChetanaL09** [comment]
Please assign this to me for Python
