### ISSUE TITLE
9 | Palindrome Number | C++

### ISSUE THREAD

**Issue by ravjotkaamra** [SHY-Corp/LeetCode-Solutions#477]
## **`Title`** -

**What will change** - Improving Code

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Improving Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by ravjotkaamra** [comment]
There are some redundant else statements in the code and boolean value can be used instead of integer c for better readability, and a bit of space optimization.

**Comment by ravjotkaamra** [comment]
Can you assign this to me, please?

**Comment by Rajeet10** [comment]
can you assign this one plz?

**Comment by nausherofficial** [comment]
would you please assign this to me
