### ISSUE TITLE
14 | Longest Common Prefix | Python

### ISSUE THREAD

**Issue by devanshkaria88** [SHY-Corp/LeetCode-Solutions#478]
## **`Longest Common Prefix`** -

**What will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [x] Python
- [ ] C++
- [ ] Java
- [ ] SQL

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by devanshkaria88** [comment]
Please Assign this problem to me  @Yashica7 @SSKale1

**Comment by sb19** [comment]
@SSKale1 @Yashica7  
can you please give the path where problem description is available.
