### ISSUE TITLE
1614 | Maximum Nesting Depth of the Parentheses | C++

### ISSUE THREAD

**Issue by pranav7955** [SHY-Corp/LeetCode-Solutions#480]
## **`Title`** - 1614. Maximum Nesting Depth of the Parentheses

**What will change** - 
Adding problem 1614. Maximum Nesting Depth of the Parentheses and solution to it

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by RachanaKampli** [comment]
Hey @pranav7955 can you assign this to me?

**Comment by Yashica7** [comment]
@pranav7955 Do u want to get assigned to this?

**Comment by pranav7955** [comment]
> @pranav7955 Do u want to get assigned to this?

Yes please assign it to me, i will open new issues for other to contribute soon :)

**Comment by pranav7955** [comment]
> Hey @pranav7955 can you assign this to me?

Hi @RachanaKampli , I have opened a new issue #512 for you and i hope that's fine with you :) 
Also, can you comment once again at #512 & don't forget you have to wait for this issue to be assigned to you, then only you can open a valid PR.
