### ISSUE TITLE
1313 | Decompress Run-Length Encoded List | C++

### ISSUE THREAD

**Issue by pranav7955** [SHY-Corp/LeetCode-Solutions#481]
## **`Title`** - 1313. Decompress Run-Length Encoded List

**What will change** -
Add problem 1313. Decompress Run-Length Encoded List and its solution

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by Mannan2812** [comment]
Please assign this to me @Yashica7 and @SSKale1
