### ISSUE TITLE
1 | TwoSum| C++

### ISSUE THREAD

**Issue by MatheusNtg** [SHY-Corp/LeetCode-Solutions#484]
## **`Fix indentation of code`** -

**Fix a problem with the indentation of the code** -

### Type of Issue -

Please add/delete options that are not relevant.

- [ ] Adding New Code
- [x] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [ ] Python
- [x] C++
- [ ] Java
- [ ] SQL

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by ambuj2000** [comment]
please assign me

**Comment by Bhaswati-Saha** [comment]
please assign it to me.

**Comment by aarush-ittan** [comment]
please assign it to me . I am new to hacktoberfest and want to learn  and do more in it.

**Comment by Yashica7** [comment]
@MatheusNtg I don't think Indentation is such a major issue unless its python
