### ISSUE TITLE
91 | Decode Ways | C++

### ISSUE THREAD

**Issue by SuryankDixit** [SHY-Corp/LeetCode-Solutions#485]
## **`Decode Ways`** -

**Addding New Code** -

### Type of Issue -
- [x] Adding New Code

### Programming Language
- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by Mannan2812** [comment]
Please assign this issue to me. @SuryankDixit

**Comment by Mannan2812** [comment]
@SSKale1 @Yashica7

**Comment by Yashica7** [comment]
@Mannan2812 You can create an issue and get assigned to it

**Comment by SuryankDixit** [comment]
Thank You @Yashica7
