### ISSUE TITLE
75 | Sort Colors | Java

### ISSUE THREAD

**Issue by piyush-kash** [SHY-Corp/LeetCode-Solutions#487]
## **`Title`** - Sort Colors

**What will change** -

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] Java

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by sidoknowia** [comment]
Hi @piyush-kash  - Can you please assign this to me?

**Comment by adhi-2311** [comment]
Can you please assign this to me @piyush-kash .

**Comment by piyush-kash** [comment]
please assign this issue to me @Yashica7 @SSKale1

**Comment by piyush-kash** [comment]
> 
> 
> Hi @piyush-kash - Can you please assign this to me?

i can't .the owner can

**Comment by adhi-2311** [comment]
Can you please assign this to me @Yashica7 @SSKale1

**Comment by Yashica7** [comment]
@adhi-2311 You can create an issue and get assigned to it

**Comment by piyush-kash** [comment]
Can i just add a new file in the Java folder of your repo and then make a PR linking my issue?? @Yashica7 @SSKale1

**Comment by piyush-kash** [comment]
Can i just add a new file in the Java folder of your repo and then make a PR linking my issue?? because its my first time and i dont know any other method @Yashica7 @SSKale1
