### ISSUE TITLE
64 | Minimum Path Sum | Python

### ISSUE THREAD

**Issue by sidoknowia** [SHY-Corp/LeetCode-Solutions#496]
## **`Minimum Path Sum`** 

**New Issue(solution)** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by sidoknowia** [comment]
@SSKale1 @Yashica7 Please assign this issue to me

**Comment by 96RadhikaJadhav** [comment]
Could you please assign this issue to me? I would like to work on it.
