### ISSUE TITLE
73 | Set Matrix Zeroes | Python

### ISSUE THREAD

**Issue by piyush-kash** [SHY-Corp/LeetCode-Solutions#501]
## **`Title`** - Set Matrix Zeroes 

**What will change** -

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] Python

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by piyush-kash** [comment]
please assign me this @Yashica7 @SSKale1

**Comment by NavyaIyanampudi** [comment]
What will change -Add a c++ code

Type of Issue -
 Adding New Code

Programming Language
 c++

Self Check
Ask for issue assignment and wait to get assigned to it before making Pull Request.
Add your file in the proper folder
Clean Code and Documentation for better readability
Add Title and Description of the program in the file
🌟 Star it 🍴Fork it 🤝 Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by NavyaIyanampudi** [comment]
Please assign me this task

**Comment by piyush-kash** [comment]
> 
> 
> Please assign me this task

Create a new issue of a new problem then only u will be assigned by the maintainer

**Comment by NavyaIyanampudi** [comment]
TITLE: 1461.Check If A String Contains All Binary Codes Of Size K
What will change -

Type of Issue -
Adding New Code

Programming Language
c++

Self Check
Ask for issue assignment and wait to get assigned to it before making Pull Request.
Add your file in the proper folder
Clean Code and Documentation for better readability
Add Title and Description of the program in the file
🌟 Star it 🍴Fork it 🤝 Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by NavyaIyanampudi** [comment]
@piyush-kash Please assign this task to me
