### ISSUE TITLE
43 | Multiply Strings | Python

### ISSUE THREAD

**Issue by Curiouspaul1** [SHY-Corp/LeetCode-Solutions#508]
## **`Multiply Strings`** -

**New Code (Solution)** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by Curiouspaul1** [comment]
@SSKale1 @Yashica7 Could you please assign this issue to me.

**Comment by sb19** [comment]
@SSKale1 @Yashica7 please assign this issue to me ...happy to provide the solution.
