### ISSUE TITLE
1365 | How Many Numbers Are Smaller Than the Current Number | C++

### ISSUE THREAD

**Issue by pranav7955** [SHY-Corp/LeetCode-Solutions#512]
## **`Title`** - 1365. How Many Numbers Are Smaller Than the Current Number

**What will change** -

Add a new problem set and solution to it

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by pranav7955** [comment]
Please assign this to @RachanaKampli :)

**Comment by swaingotnochill** [comment]
We can't do that unless she volunteers herself.

**Comment by RachanaKampli** [comment]
Can you assign this to me?
