### ISSUE TITLE
85. | Maximal Rectangle | C++

### ISSUE THREAD

**Issue by jatin831** [SHY-Corp/LeetCode-Solutions#513]
## **Maximal Rectangle** -

**What will change** -

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by swaingotnochill** [comment]
Unless the issue is assigned to you, you should not make a PR. This is treated as spam.

**Comment by DEBADRIBASAK** [comment]
Please assign this issue to me

**Comment by DEBADRIBASAK** [comment]
I have already made a PR. Please assign this issue and approve my request

**Comment by jatin831** [comment]
So assign some issue for me. I will do it.
