### ISSUE TITLE
48 | Rotate Image | C++

### ISSUE THREAD

**Issue by sau-rav** [SHY-Corp/LeetCode-Solutions#522]
## **`Rotate Image`** -

**What will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by sau-rav** [comment]
Please assign the issue to me

**Comment by swaingotnochill** [comment]
There's already a solution for this. Unless you mention how you will modify and improve the code,  I can't assign this to you .
