### ISSUE TITLE
239 | Sliding Window Maximum | C++

### ISSUE THREAD

**Issue by sau-rav** [SHY-Corp/LeetCode-Solutions#528]
## **`Sliding Window Maximum`** -

**What will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by sau-rav** [comment]
The solution to sliding window maximum is not available, please assign it to me I will add the solution

**Comment by dhyanid13** [comment]
I would like to provide an efficient solution to this can you please assign it to me?

**Comment by abhay27chauhan** [comment]
would love ans this. Can you pls assign it to me?

**Comment by SSKale1** [comment]
- [x] Assigning to @sau-rav for issue creation.
