### ISSUE TITLE
58 | Length of Last Word | C++

### ISSUE THREAD

**Issue by shivanshuman021** [SHY-Corp/LeetCode-Solutions#531]
## **Length of Last Word** - 

**What will change** -

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by RishavHimmatramka** [comment]
Can you please assign this issue to me?

**Comment by nikhil05-code** [comment]
Please assign it to me.

**Comment by dhyanid13** [comment]
Could you please assign this to me?

**Comment by anuj840** [comment]
Please assign it to me.

**Comment by edge555** [comment]
Please assign it to me. I can do this.

**Comment by bhantsi** [comment]
I can do this, assign it to me

**Comment by CRJain** [comment]
Hey, can you please assign this issue to me?
