### ISSUE TITLE
442 | Find All Duplicates in an Array | java

### ISSUE THREAD

**Issue by KILLERKILLAM** [SHY-Corp/LeetCode-Solutions#546]
## **`Title`** -Find All Duplicates in an Array in java

**What will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [] Improving Code
- [] Improving Documentation
- [] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [] Python
- [] C++
- [x] Java
- [] SQL

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by jaisaikuntala1** [comment]
Can you assign this to me?

**Comment by nikhil05-code** [comment]
Please assign it to me.

**Comment by sb19** [comment]
please assign this issue to me.

**Comment by SSKale1** [comment]
- [x] Assigning to @KILLERKILLAM  for issue creation.
