### ISSUE TITLE
1310 | XOR Queries of a Subarray | Java

### ISSUE THREAD

**Issue by ankitvd6** [SHY-Corp/LeetCode-Solutions#554]
## **`Title`** - XOR Queries of a Subarray

**What will change** - New Java solution will be added faster than 100.00% of Java online submissions.

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] Java

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by ankitvd6** [comment]
@SSKale1 @Yashica7 I would like to work on this. Can you please assign this to me.

**Comment by sethivansh6** [comment]
@Yashica7 I would like to work on this and any other issue you want me to. Assign me!
