### ISSUE TITLE
300 |  Longest Increasing Subsequence | C++

### ISSUE THREAD

**Issue by keshavga1209** [SHY-Corp/LeetCode-Solutions#559]
## **`Title`** - Longest Increasing Subsequence

**What will change** -
Adding Code for a new problem

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [ ] Python
- [x] C++
- [ ] Java
- [ ] SQL

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by keshavga1209** [comment]
I am interested in doing this problem. Can you please assign it to me?

**Comment by edge555** [comment]
Assign to me, please.

**Comment by abhay27chauhan** [comment]
@SSKale1 @Yashica7 can you pls assign me this task
