### ISSUE TITLE
51 | N-Queens | C++

### ISSUE THREAD

**Issue by AaronF3PS** [SHY-Corp/LeetCode-Solutions#562]
## **N-Queens** -

**Included printing all solutions for the problem** -

### Algorithm Based-Backtracking -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Code
- [x] Improving Documentation
- [x] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

**Comment by AaronF3PS** [comment]
Feel free to assign me this task

**Comment by abhay27chauhan** [comment]
@SSKale1 @Yashica7 can you pls assign me this task

**Comment by AaronF3PS** [comment]
@SSKale1 I have completed and PR. Kindly review and merge
