### ISSUE TITLE
78 | Subsets | Java

### ISSUE THREAD

**Issue by ankitvd6** [SHY-Corp/LeetCode-Solutions#563]
## **`Title`** - Subsets

**What will change** - Java Solution added for the Problem. Runtime: 0 ms, faster than 100.00% of Java online submissions for Subsets.

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] Java

**Comment by ankitvd6** [comment]
@SSKale1 @Yashica7 Can you please assign this to me.

**Comment by abhay27chauhan** [comment]
@SSKale1 @Yashica7 can you pls assign me this one

**Comment by SSKale1** [comment]
@ankitvd6 Cooldown for sometime we'll assign this one to @abhay27chauhan

**Comment by ankitvd6** [comment]
> @ankitvd6 Cooldown for sometime we'll assign this one to @abhay27chauhan

Hahaha.. Sure @SSKale1 no issues.
