### ISSUE TITLE
121 | Best Time to Buy and Sell Stock  | Java

### ISSUE THREAD

**Issue by abhay27chauhan** [SHY-Corp/LeetCode-Solutions#565]
## **`Title`** - Best Time to Buy and Sell Stock 

**What will change** - Java solution will be added for the problem

### Type of Issue -
- [x] Adding New Code

### Programming Language
- [x] Java

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by abhishtjoshi** [comment]
@SSKale1 @Yashica7 can you pls assign me this one

**Comment by abhay27chauhan** [comment]
Do I have to change the class name to the file name or let it be "Solution" like the rest

**Comment by abhay27chauhan** [comment]
@SSKale1 @Yashica7 I have completed and made PR. Kindly review and merge
