### ISSUE TITLE
1588 | Sum of All Odd Length Subarrays | C++

### ISSUE THREAD

**Issue by rituraj735** [SHY-Corp/LeetCode-Solutions#569]
## **`Title`** - Sum of All Odd Length Subarrays

**What will change** - C++ solution for the problem will be added 

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [] Improving Code
- [] Improving Documentation
- [] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [] Python
- [x] C++
- [] Java
- [] SQL

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by SaShaShady** [comment]
Pls assign this to me

**Comment by rituraj735** [comment]
Feel free to assign me the issue @Yashica7 @SSKale1

**Comment by nikhil05-code** [comment]
Please assign it to me.

**Comment by swetakyada** [comment]
Please Assign it to me.
