### ISSUE TITLE
205 | Isomorphic Strings | Python

### ISSUE THREAD

**Issue by wpedrak** [SHY-Corp/LeetCode-Solutions#57]
## **`Title`** - 205. Isomorphic Strings 

**What will change** - Adding solution

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [x] Python
- [ ] C++
- [ ] Java
- [ ] SQL

**Comment by wpedrak** [comment]
Please assign it to me.

**Comment by SSKale1** [comment]
- [x] Assigning to @wpedrak
