### ISSUE TITLE
236 | Lowest Common Ancestor of a Binary Tree | C++

### ISSUE THREAD

**Issue by nyctophiliacme** [SHY-Corp/LeetCode-Solutions#571]
## **`Lowest Common Ancestor of a Binary Tree`** -

**What will change** - Adding code for a new problem

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by nyctophiliacme** [comment]
@SSKale1 Can you please assign it to me.

**Comment by abhishtjoshi** [comment]
@SSKale1 @Yashica7 can you pls assign me this one
