### ISSUE TITLE
102 l Binary Tree Level Order Traversal | C++

### ISSUE THREAD

**Issue by jaisaikuntala1** [SHY-Corp/LeetCode-Solutions#576]
## **`Title`** - Binary Tree Level Order Traversal

**What will change** - A new code will be added.

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by jaisaikuntala1** [comment]
Assign this to me and I'll get the job done!

**Comment by abhishtjoshi** [comment]
@SSKale1 @Yashica7 can you pls assign me this one

**Comment by NavyaIyanampudi** [comment]
Please assign this to me
