### ISSUE TITLE
21 | Merge Two Sorted Lists | C++

### ISSUE THREAD

**Issue by aditya-gupta-i** [SHY-Corp/LeetCode-Solutions#585]
## **`Title`** - Merge Two Sorted Lists

**What will change** - C++ solution will be added for the problem

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by aditya-gupta-i** [comment]
@Yashica7 @SSKale1 Could you kindly assign me this problem?

**Comment by nikhil05-code** [comment]
Please assign it to me.

**Comment by swetakyada** [comment]
Can you please assign this problem to me?

**Comment by arpit7714** [comment]
issue already present #542

**Comment by NavyaIyanampudi** [comment]
could you please assign me this problem?
