### ISSUE TITLE
2 | Add Two Numbers(Medium) | C++

### ISSUE THREAD

**Issue by pranshta** [SHY-Corp/LeetCode-Solutions#588]
## **`Title`** -Add Two Numbers(Medium)

**What will change** - A new C++ solution will be added.

### Type of Issue -
- [x] Adding New Code

### Programming Language

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by pranshta** [comment]
@Yashica7 @SSKale1   Please assign this issue to me

**Comment by nikhil05-code** [comment]
Please assign it to me.

**Comment by anuj840** [comment]
Please assign it to me.

**Comment by anuj840** [comment]
please assign it
