### ISSUE TITLE
7 | sort | C++

### ISSUE THREAD

**Issue by chiragoyal** [SHY-Corp/LeetCode-Solutions#589]
## **`sort`** -

**What will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [1] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [ ] Python
- [1] C++
- [ ] Java
- [ ] SQL

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by Akashsahu1998** [comment]
@Yashica7 @SSKale1 please assign this issue to me!

**Comment by nikhil05-code** [comment]
Please assign it to me.
