### ISSUE TITLE
263 | Ugly Number | Python

### ISSUE THREAD

**Issue by aniakubik** [SHY-Corp/LeetCode-Solutions#59]
## **`Title`** - 263. Ugly Number

**What will change** - Adding solution

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [x] Python
- [ ] C++
- [ ] Java
- [ ] SQL

**Comment by SSKale1** [comment]
- [x] Assigned to @aniakubik

**Comment by chehak123** [comment]
Please assign to me also

**Comment by anthonybench** [comment]
I'd love to be assigned to this please!
