### ISSUE TITLE
1295 | Find_Number_with_even | C++

### ISSUE THREAD

**Issue by Akashsahu1998** [SHY-Corp/LeetCode-Solutions#592]
## **`Title`** -

**What will change** - 
A simple, new C++ solution will be added.

### Type of Issue -
Adding New Code

### Programming Language
C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by Akashsahu1998** [comment]
@Yashica7 @SSKale1 Please assign this issue to me.

**Comment by pratik-2020** [comment]
@Akashsahu1998  Please assign me this issue
