### ISSUE TITLE
125 | Valid Palindrome | C++

### ISSUE THREAD

**Issue by Nyctophiliac1918** [SHY-Corp/LeetCode-Solutions#594]
## **`Title`** - Valid Palindrome

**What will change** - A simple and new C++ solution will be added.

### Type of Issue -

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

- [ ] Python
- [x] C++
- [ ] Java
- [ ] SQL

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by Nyctophiliac1918** [comment]
@Yashica7 @SSKale1 Please assign this issue to me!

**Comment by pranshta** [comment]
@Yashica7  I would like to do this.

**Comment by arpitg24** [comment]
Can you please assign this issue to me?

**Comment by sb19** [comment]
@Yashica7 @SSKale1 please assign this issue to me...thanks.

**Comment by surya-x** [comment]
@Yashica7 @SSKale1 Please assign this to me. I can implement it on both Python and Java.

**Comment by swaingotnochill** [comment]
surya it will be better if you could raise an issue. The task will be assigned as per preferences.

**Comment by prerna250** [comment]
Can you please assign this to me. I'll do it in python language
