### ISSUE TITLE
14 | Longest Common Prefix | C++

### ISSUE THREAD

**Issue by ManviGoel26** [SHY-Corp/LeetCode-Solutions#610]
## Longest Common Prefix

**What will change** - Add the code to the problem

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by ManviGoel26** [comment]
Can I contribute to this?

**Comment by nikhil05-code** [comment]
Please assign it to me.

**Comment by Sumanya312** [comment]
Could you please assign this to me
