### ISSUE TITLE
235 |Lowest Common Ancestor of a Binary Search Tree  | C++

### ISSUE THREAD

**Issue by vidhya001** [SHY-Corp/LeetCode-Solutions#612]
## **`Title`** -Lowest Common Ancestor of a Binary Search Tree    

**What will change** -Add C++ code to find Lowest Common Ancestor of a Binary Search Tree    

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by vidhya001** [comment]
please assign this to me

**Comment by Sumanya312** [comment]
Please assign this issue to me
