### ISSUE TITLE
51 | N-Queens | C++

### ISSUE THREAD

**Issue by AaronF3PS** [SHY-Corp/LeetCode-Solutions#617]
## **N-Queens** -

**Using Backtracing Algorithm** -

### Hard -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Code
- [x] Improving Documentation
- [x] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by AaronF3PS** [comment]
Please feel free to assign me this task.

**Comment by anuj840** [comment]
please assign 51 | N-Queens | C++ #617 me

**Comment by AaronF3PS** [comment]
Yes i completed and PR. Kindly review and merge.
