### ISSUE TITLE
804 | Unique Morse Code Words | C++

### ISSUE THREAD

**Issue by UmaMaheswariGorusupudi** [SHY-Corp/LeetCode-Solutions#626]
## **`Title`** -

**What will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [] Improving Code
- [] Improving Documentation
- [] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [] Python
- [x] C++
- [] Java
- [] SQL

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by NafiAsib** [comment]
Please assign this issue to me

**Comment by Yashica7** [comment]
@UmaMaheswariGorusupudi Do u want to get assigned to it?

**Comment by swaingotnochill** [comment]
I am assigning this to @NafiAsib as there was no reply from @UmaMaheswariGorusupudi side.

**Comment by UmaMaheswariGorusupudi** [comment]
Assign it to me
