### ISSUE TITLE
135 | Candy | C++

### ISSUE THREAD

**Issue by 48cfu** [SHY-Corp/LeetCode-Solutions#629]
## **` Candy`** -

**What will change** -  A well documented and clean C++ solution will be added.

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

**Comment by 48cfu** [comment]
Please assign this issue to me

**Comment by ritik-sys** [comment]
Hey There!! Can You plese assign this to me??
