### ISSUE TITLE
1172 | Dinner Plate Stacks | C++

### ISSUE THREAD

**Issue by 48cfu** [SHY-Corp/LeetCode-Solutions#632]
## **`Dinner Plate Stacks`** -

**What will change** - A well documented and clean C++ solution will be added.

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

**Comment by 48cfu** [comment]
Please assign this issue to me

**Comment by DaRkSouL-1** [comment]
assign me plz
