### ISSUE TITLE
239 | Sliding Window Maximum | C++

### ISSUE THREAD

**Issue by 48cfu** [SHY-Corp/LeetCode-Solutions#634]
## **`Sliding Window Maximum`** -

**What will change** - A well documented and clean C++ solution will be added.

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

**Comment by 48cfu** [comment]
Please assign this issue to me

**Comment by ritik-sys** [comment]
Hey There!! Can You plese assign this to me??

**Comment by hitch-hiker42** [comment]
I have written the code for the mentioned problem and will be glad to help if you assign me for the same.

**Comment by SSKale1** [comment]
This problem already exists in the codebase.
