### ISSUE TITLE
27 | Remove Element | C++

### ISSUE THREAD

**Issue by vasu2907** [SHY-Corp/LeetCode-Solutions#636]
## **`Remove Element`** -

**What will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by dougnobrega** [comment]
Assign me plz

**Comment by dougnobrega** [comment]
@Yashica7 @SSKale1 assign me plz

**Comment by Yashica7** [comment]
@vasu2907 Do u want to get assigned to this?

**Comment by vasu2907** [comment]
@Yashica7 Yes please assign me this issue.
