### ISSUE TITLE
53 | Maximum Subarray | C++

### ISSUE THREAD

**Issue by aforanushka** [SHY-Corp/LeetCode-Solutions#641]
## 53 | Maximum Subarray | C++

**What will change** -

Added solution for Maximum Sub Array problem

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] C++

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by aforanushka** [comment]
Please assign this to me

**Comment by ritik-sys** [comment]
Hey there! Can u please assign this to me ?
