### ISSUE TITLE
977 | Squares of a Sorted Array| Python

### ISSUE THREAD

**Issue by wpedrak** [SHY-Corp/LeetCode-Solutions#65]
## **`Title`** - 977. Squares of a Sorted Array

**What will change** - Solution of problem 977 in python

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [x] Python
- [ ] C++
- [ ] Java
- [ ] SQL

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by wpedrak** [comment]
Please assign me

**Comment by SSKale1** [comment]
- [x]  Assigned to @wpedrak

**Comment by chehak123** [comment]
Please assign to me also
