### ISSUE TITLE
invalid

### ISSUE THREAD

**Issue by RishavHimmatramka** [SHY-Corp/LeetCode-Solutions#672]
## **Recover a Tree From Preorder Traversal** -

**Add C++ code** 

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [] Improving Code
- [] Improving Documentation
- [] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [] Python
- [x] C++
- [] Java
- [] SQL

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by RishavHimmatramka** [comment]
Pls assign this issue to me.

**Comment by shinchancode** [comment]
please assign this to me

**Comment by SSKale1** [comment]
This issue is now open for assignment.
