### ISSUE TITLE
396 | Rotate Function | C++

### ISSUE THREAD

**Issue by Riei-Joaquim** [SHY-Corp/LeetCode-Solutions#673]
## **`Title`** - Rotate Function 

**What will change** -Add C++ code to 396. Rotate Function

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by pawki07** [comment]
Hey, I would like to work on this issue. Please assign it to me.

**Comment by pawki07** [comment]
Okay, Thanks
