### ISSUE TITLE
2 | Add Two Numbers | CPP

### ISSUE THREAD

**Issue by mayankaggarwal098** [SHY-Corp/LeetCode-Solutions#677]
## **`Title`** - Add Two Numbers

**What will change** - new solution 

### Type of Issue - adding a new solution

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by pawki07** [comment]
Please assign it to me.

**Comment by NavyaIyanampudi** [comment]
Please assign it to me.

**Comment by harshulab** [comment]
I would love to work on this issue! Kindly assign it to me. 
Regards

**Comment by preeti13456** [comment]
Interested

**Comment by pranshta** [comment]
Issue has already been raised and assigned for this problem in #588

**Comment by orvil1026** [comment]
Please assign this issue to me.

**Comment by swaingotnochill** [comment]
@mayankaggarwal098 do you wanna work on this issue or not?

**Comment by pawki07** [comment]
Yes, I would like to work on this issue but it has not been assigned to me
yet.
