### ISSUE TITLE
21 | Merge Two Sorted Lists | C++

### ISSUE THREAD

**Issue by rituraj735** [SHY-Corp/LeetCode-Solutions#684]
## **`Title`** - Merge Two Sorted Lists

**What will change** - A C++ solution for the problem will be added

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by divyagupta-98** [comment]
Please assign this to me.

**Comment by preeti13456** [comment]
Interested

**Comment by preeti13456** [comment]
I have solved it already

**Comment by SSKale1** [comment]
This problem already exists in the codebase.
