### ISSUE TITLE
338 | Counting Bits | C++

### ISSUE THREAD

**Issue by suffisme** [SHY-Corp/LeetCode-Solutions#685]
## **`Counting Bits`** -

**What will change** -  A well written dp code and clean C++ solution will be added.

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by suffisme** [comment]
Hey
Please assign this issue to me.

**Comment by pardeep596** [comment]
can i do this in java

**Comment by SSKale1** [comment]
This problem already exists in the codebase.
