### ISSUE TITLE
118 | Pascal's Triangle | C++

### ISSUE THREAD

**Issue by rituraj735** [SHY-Corp/LeetCode-Solutions#690]
## **`Title`** - Pascal's Triangle

**What will change** - C++ code for the problem will be added

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by ritviksharma3** [comment]
Hi ! Can you assign me this issue ?

**Comment by SrijitaSarkar99** [comment]
Hey! I can work on this issue. Can you assign me this?

**Comment by anushkasethi1710** [comment]
Hi ! Can you assign me this issue ?

**Comment by ritviksharma3** [comment]
Thank you for assigning @SSKale1 
Will get it done ASAP

**Comment by ritviksharma3** [comment]
@SSKale1 Hi ! Please review PR #865 for issue #690

**Comment by ritviksharma3** [comment]
@SSKale1 Hi ! Please review file with #866 for issue #690 
Please commit the code with the "Update" description, that is the right solution.
