### ISSUE TITLE
1480 | Running Sum of 1d Array.py | Python

### ISSUE THREAD

**Issue by ngandhi369** [SHY-Corp/LeetCode-Solutions#692]
## **`Title`** - 1480. Running Sum of 1d Array.py

**What will change** - 
Added a new file 

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] Python

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

**Comment by SSKale1** [comment]
This problem already exists in the codebase.
