### ISSUE TITLE
844. | Backspace String Compare | C++

### ISSUE THREAD

**Issue by suffisme** [SHY-Corp/LeetCode-Solutions#696]
## **`Backspace String Compare`** -

**What will change** - A new well documented and efficient code using STACKS (as Data Structure) will be added.

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.
- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by abhishtjoshi** [comment]
Please assign it to me

**Comment by suffisme** [comment]
Please assign this issue to me.
