### ISSUE TITLE
1 | Two Sum | Python 

### ISSUE THREAD

**Issue by SSKale1** [SHY-Corp/LeetCode-Solutions#7]
## **`Title`** - 1. Two Sum Problem

**What will change** -
### Type of Issue -
- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/Ftbj4a

Happy Coding,

**Comment by AryashDubey** [comment]
Hey Can I Work On this Please?

**Comment by SSKale1** [comment]
Sure.

- [x] Assigned to @AryashDubey . 
Make sure you read and follow the contribution guidelines. And submit according to the Leetcode Solution with proper Comments explaining the program and Time/Space Complexities if Applicable.
