### ISSUE TITLE
26 | Remove Duplicates from Sorted Array | C++

### ISSUE THREAD

**Issue by NafiAsib** [SHY-Corp/LeetCode-Solutions#701]
## **`Title`** - Remove Duplicates from Sorted Array

**What will change** - C++ solution for the problem will be added

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by NafiAsib** [comment]
Please assign this issue to me

**Comment by pardeep596** [comment]
I can do this in java and c++
