### ISSUE TITLE
21 | Merge Two Sorted Lists | C++

### ISSUE THREAD

**Issue by Rishabh-Thapliyal** [SHY-Corp/LeetCode-Solutions#715]
## **`Title`** - Merge Two Sorted Lists

**What will change** -  Add C++ code to 21. Merge Two Sorted Lists

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by Rishabh-Thapliyal** [comment]
Please assign this issue to me.

**Comment by sentyhu** [comment]
plz assign this issue to me

**Comment by drewmich** [comment]
Hi, can you assign me the issue?

**Comment by SSKale1** [comment]
This problem already exists in the codebase.
