### ISSUE TITLE
1189 | Maximum Number of Balloons | Python

### ISSUE THREAD

**Issue by aniakubik** [SHY-Corp/LeetCode-Solutions#72]
## **`Title`** - 1189. Maximum Number of Balloons

**What will change** - Adding a solution.

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [x] Python
- [ ] C++
- [ ] Java
- [ ] SQL

**Comment by aniakubik** [comment]
Please assign me.

**Comment by SSKale1** [comment]
- [x] Assigned to @aniakubik
