### ISSUE TITLE
572 | Subtree of Another Tree | Java

### ISSUE THREAD

**Issue by abhishtjoshi** [SHY-Corp/LeetCode-Solutions#724]
## **`Title`** - Subtree of Another Tree

**What will change** - Add solution to the problem in java language

### Type of Issue -
- [x] Adding New Code

### Programming Language
- [x] Java

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by abhishtjoshi** [comment]
@SSKale1 @Yashica7 can you pls assign me this task

**Comment by rahul975337** [comment]
please assign this to me
