### ISSUE TITLE
799 | Champagne Tower | C++

### ISSUE THREAD

**Issue by ccocz** [SHY-Corp/LeetCode-Solutions#725]
## **`Title`** - 799. Champagne Tower

**What will change** - C++ solution for 799. Champagne Tower

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by harshitsankhla** [comment]
@ccocz please assign me to this

**Comment by sarita1124** [comment]
Please assign me this.

**Comment by rahul975337** [comment]
please assign this to me

**Comment by ccocz** [comment]
@Yashica7 @SSKale1 please assign this issue to me.

**Comment by ccocz** [comment]
@swaingotnochill please assign this issue to me.
