### ISSUE TITLE
307 | Range Sum Query - Mutable | Java

### ISSUE THREAD

**Issue by adhi-2311** [SHY-Corp/LeetCode-Solutions#728]
## **`Title`** - 307. Range Sum Query - Mutable

**What will change** -
Java solution involving segment tree approach would be added for Range Sum Query - Mutable

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language
- [x] Java

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by adhi-2311** [comment]
@Yashica7 @SSKale1 can you please assign this to me

**Comment by rahul975337** [comment]
please assign it to me
