### ISSUE TITLE
1470 | Shuffle the array | C++

### ISSUE THREAD

**Issue by muskanlalit18** [SHY-Corp/LeetCode-Solutions#730]
## **Shuffle The Array** -

**What will change** -

Add C++  script for 1470. Shuffle the array

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by muskanlalit18** [comment]
Please assign this issue to me.

**Comment by sentyhu** [comment]
please assign this issue to me
