### ISSUE TITLE
1019 | Next Greater Node In Linked List | Java

### ISSUE THREAD

**Issue by pranav2437** [SHY-Corp/LeetCode-Solutions#731]
## **`Title`** - 1019 Next greater node in Linked List

**What will change** - Java solution for 1019. Next greater node in linked list will be added

### Type of Issue -

-  [x] Adding New Code

### Programming Language 

- [x] Java

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by pranav2437** [comment]
@Yashica7 @SSKale1 , I would like to contribute, please assign this issue to me.

**Comment by SSKale1** [comment]
Issue #505 Already exists for the same problem.
