### ISSUE TITLE
142 | LinkedListCycle | C++

### ISSUE THREAD

**Issue by ravjotkaamra** [SHY-Corp/LeetCode-Solutions#736]
## **`Title`** - LinkedListCycle

**What will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Improving Code
- [x] Improving Documentation

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by ravjotkaamra** [comment]
- nullptr could be used instead of NULL as mentioned in the stackoverflow

- 'and' keyword could cause confusion between logical AND and bitwise AND so && should be used

- I  think flag = 1 should mean that there's a cycle but in the code its the reverse.

- A little error in the documentation about time complexity of algorithm

**Comment by davbrito** [comment]
I would like to work on this issue.

**Comment by ravjotkaamra** [comment]
Could you assign this to me, please!! I forgot to mention this before

**Comment by davbrito** [comment]
Another think that can be fixed is to use the data member initializer syntax.

At this moment the code is:
> ```C++
> struct node
> {
> 	int val;
> 	node *next;
> 	node(int x)
> 	{
> 		val=x;
> 		next=nullptr;
> 	}
> };
> ```

And it would be better to use the correct syntax:
```C++
struct node
{
	int val;
	node *next;
	node(int x) : val{x}, next{nullptr} { }
};
```

**Comment by ravjotkaamra** [comment]
Wow! So you basically assigned my suggestions to someone else and he just had to type those things up. That's unfair.

**Comment by SSKale1** [comment]
@ravjotkaamra sorry about the mixup, but its done now. You can make an issue for any other problem we'll make sure to assign it to you.

**Comment by ravjotkaamra** [comment]
Sir, it's very disheartening when somebody takes credit for your work, atleast let me have some kind of contribution in this code. Please, sir look into this issue.

**Comment by SSKale1** [comment]
We have space for a lot of contributions. You can create another Issue and it'll be assigned to you.

**Comment by ravjotkaamra** [comment]
This is not the point. The point is to stop this from happening. What if other users start doing this and take credit for others contribution. You should take action against those who plagiarize.

**Comment by SSKale1** [comment]
It is not exactly plagiarism @ravjotkaamra @davbrito understood the issue you had raised and had made proper changes to the code and added his input too. The assignment may have been mixed up, but this is open source you can't call this plagiarism too. I'm sure you must've worked hard to find the issues that you did but this issue is now closed and we appreciate your contribution. And there's over sixteen hundred problems on LC. I'm sure you could find one that is not present in our repo. Finally, thank you for your contribution and wish nothing but the best for the community.
