### ISSUE TITLE
295 | Find Median from Data Stream | Python

### ISSUE THREAD

**Issue by Melvin-Abraham** [SHY-Corp/LeetCode-Solutions#737]
## **`Title`** - Find Median from Data Stream

**What will change** - Addition of new solution for **"295. Find Median from Data Stream"** in _Python_

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [x] Python
- [ ] C++
- [ ] Java
- [ ] SQL

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife: Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by Melvin-Abraham** [comment]
I would love to work on this issue...

**Comment by potter1024** [comment]
I would love to work on the C++ part of it.
