### ISSUE TITLE
1605 | Find Valid Matrix Given Row and Column Sums | C++

### ISSUE THREAD

**Issue by freakcap** [SHY-Corp/LeetCode-Solutions#738]
## **`Title`** -  Find Valid Matrix Given Row and Column Sums (1605)
 
**What will change** - New well documented solution will be added.

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] C++

**Comment by freakcap** [comment]
Waiting for assignment.

**Comment by SaxenaKartik** [comment]
I would like to work on this issue
