### ISSUE TITLE
977 |  SquaresOfASortedArray | C++

### ISSUE THREAD

**Issue by ravjotkaamra** [SHY-Corp/LeetCode-Solutions#739]
## **`Title`** - SquaresOfASortedArray

**What will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Improving Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by ravjotkaamra** [comment]
Since we already know the size of the array which has to be returned we should define the size while declaring vector B and  push_back could be replaced by assignment.
This should be done in case push_back leads to resizing of the vector which takes up O(n) time

**Comment by ravjotkaamra** [comment]
Could you assign this to me, please!! I forgot to mention this before

**Comment by ravjotkaamra** [comment]
Could you assign this to me, please?

**Comment by SSKale1** [comment]
This problem already exists in the codebase.

**Comment by ravjotkaamra** [comment]
I saw the code and it's not fixed. I don't understand what you mean, could you explain?

**Comment by SSKale1** [comment]
Oh sorry my bad didn't read your comment through.
