### ISSUE TITLE
1561 | Maximum Number of Coins You Can Get | C++

### ISSUE THREAD

**Issue by freakcap** [SHY-Corp/LeetCode-Solutions#740]
## **`Title`** - Maximum Number of Coins You Can Get (1561)

**What will change** - New well documented solution will be added.

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] C++

**Comment by freakcap** [comment]
Waiting for assignment.

**Comment by iashu2k** [comment]
@freakcap plz assign this to me

**Comment by SaxenaKartik** [comment]
I would like to work on this issue
