### ISSUE TITLE
35 | Search Insert Position | C++

### ISSUE THREAD

**Issue by ksinha5nov** [SHY-Corp/LeetCode-Solutions#745]
## **Search Insert Position** -

**What will change** - Adding a new code for the problem number 35 Search Insert Position

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by PradyumnG** [comment]
@ksinha5nov Can you assign this issue to me so that I can start working on it?

**Comment by ksinha5nov** [comment]
@PradyumnG I raised this issue to solve it, I am already through with the code and just need to make a pull request. Feel free to try other problems or raise an issue.

**Comment by ksinha5nov** [comment]
@SSKale1 @Yashica7 Hey Can you please assign this to me. I want to contribute to it. Thank you.
