### ISSUE TITLE
35 | Search Insert Position | Java

### ISSUE THREAD

**Issue by Shrirang97** [SHY-Corp/LeetCode-Solutions#75]
## **`Title -  35.Search Insert Position`**

**What will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [] Improving Code
- [] Improving Documentation
- [] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [] Python
- [] C++
- [x] Java
- [] SQL

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by Shrirang97** [comment]
Assign to me!

**Comment by SSKale1** [comment]
@Shrirang97 Just make an issue for 1 Language at a time. You can create a separate issue for another language.
Edit the Issue for now.

**Comment by Shrirang97** [comment]
Ok.
