### ISSUE TITLE
49 | Group Anagrams | Python

### ISSUE THREAD

**Issue by carolinejoseph** [SHY-Corp/LeetCode-Solutions#751]
## **`Title`** - Group Anagrams Problem in Python

**What will change** - Will add a solution to problem #49 Group Anagrams in Python

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] Python

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by carolinejoseph** [comment]
Please assign this issue to me

**Comment by 96RadhikaJadhav** [comment]
Could you please assign this issue to me?
