### ISSUE TITLE
104 | Maximum Depth of Binary Tree | C++

### ISSUE THREAD

**Issue by ksinha5nov** [SHY-Corp/LeetCode-Solutions#756]
## **Maximum Depth of Binary Tree** -

**What will change** - New code for problem number 104- Maximum Depth of Binary tree

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by alexdmckee** [comment]
Hi,  I'd like to work on this issue.

**Comment by drewmich** [comment]
Hi, I'd like to be assigned this issue

**Comment by drewmich** [comment]
Hi, i'd like to be assigned this issue

**Comment by ksinha5nov** [comment]
Hi, @alexdmckee @drewmich , I raised the issue to contribute to it. i am currently looking forward to solve this one. It would be great if you could pick another one. Thank you.

**Comment by ksinha5nov** [comment]
Can you please assign this to me, Thank you.
