### ISSUE TITLE
299 | Bulls and Cows | C++

### ISSUE THREAD

**Issue by theamritanair** [SHY-Corp/LeetCode-Solutions#757]
## **`Title`** - Bulls and Cows

**What will change** - Add C++ code to problem 299

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
### Programming Language

Please add/delete options that are not relevant.
- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by theamritanair** [comment]
@Yashica7 @SSKale1

**Comment by SaxenaKartik** [comment]
I would like to work on this issue
