### ISSUE TITLE
22 | Generate Parentheses | C++

### ISSUE THREAD

**Issue by aroma6700** [SHY-Corp/LeetCode-Solutions#758]
## **`Title`** - Generate Parentheses

**What will change** - A C++ implementation for Generate Parentheses Problem

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by aroma6700** [comment]
Please assign me the issue

**Comment by hitch-hiker42** [comment]
I will be glad to help with the cause, assign me the issue.

**Comment by ankita1618** [comment]
Please assign me the issue

**Comment by drewmich** [comment]
Please assign me the issue
