### ISSUE TITLE
287 | Find the Duplicate Number | Java

### ISSUE THREAD

**Issue by efguydan** [SHY-Corp/LeetCode-Solutions#760]
## **`Title`** - Find the Duplicate Number

**What will change** - I will add a Java implemented Algorithm for the above problem.

### Type of Issue - 

- [x] Adding New Code

### Programming Language

- [x] Java

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by efguydan** [comment]
Hi, I would like to work on this issue

**Comment by matbiit** [comment]
Hi, I would like to work on this issue
