### ISSUE TITLE
118. | Pascal's Triangle | Python

### ISSUE THREAD

**Issue by AlexandreVelloso** [SHY-Corp/LeetCode-Solutions#763]
## **`Title`** - Fix error in the test case when num is zero

**What will change** - Fix the existing code

### Type of Issue - Bug Fix

Please add/delete options that are not relevant.

- [] Adding New Code
- [x] Improving Code
- [] Improving Documentation
- [x] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [x] Python
- [] C++
- [] Java
- [] SQL

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by AlexandreVelloso** [comment]
There is an error in the case when the num is zero, I can fix that

**Comment by 96RadhikaJadhav** [comment]
I would like to work on it..Could you please assign it to me?
