### ISSUE TITLE
42 | Trapping Rain Water | C++

### ISSUE THREAD

**Issue by yfancc20** [SHY-Corp/LeetCode-Solutions#77]
## **`Title`** - 42 | Trapping rain water

**What will change** -
C++ code for problem 42 Trapping rain water will be added.

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [ ] Python
- [x] C++
- [ ] Java
- [ ] SQL

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by yfancc20** [comment]
Hi, can this be assigned to me? thanks.

**Comment by Yashica7** [comment]
- [x] @yfancc20 Assigned it you

**Comment by hjpassion** [comment]
is anything left for me in this task then please assign it to me i am looking for issues where i can contribute
