### ISSUE TITLE
42 | Trapping Rain Water | Python

### ISSUE THREAD

**Issue by Shrirang97** [SHY-Corp/LeetCode-Solutions#78]
## **`Title - 42. Trapping Rain Water `** 

**What will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [] Improving Code
- [] Improving Documentation
- [] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [x] Python
- [] C++
- [] Java
- [] SQL

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by Shrirang97** [comment]
Assign to me!

**Comment by SSKale1** [comment]
- [x] Assigned to @Shrirang97

**Comment by SankethGB** [comment]
Can I write a C++ code for the same problem? Should I raise another issue or can you assign me to the same and I contribute?

**Comment by SSKale1** [comment]
@SankethGB you can raise another issue. Just check that it doesn't already exist
