### ISSUE TITLE
79| Word Search | Java

### ISSUE THREAD

**Issue by efguydan** [SHY-Corp/LeetCode-Solutions#783]
## **`Title`** - Word Search

**What will change** - I will add a Java implemented Algorithm for the above problem

### Type of Issue - 

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Java

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by jedau** [comment]
@efguydan I have a working solution in my back pocket. Would love to add it here as a contribution. It would be awesome if you could assign this to me. Thanks!

**Comment by SSKale1** [comment]
@efguydan you wanna work on this or do I assign it to @jedau

**Comment by efguydan** [comment]
Yeah, i want to work on it @SSKale1.
