### ISSUE TITLE
1627 | Graph Connectivity With Threshold | C++

### ISSUE THREAD

**Issue by af-orozcog** [SHY-Corp/LeetCode-Solutions#797]
## **`Graph Connectivity With Threshold`** -

**What will change** - New code for problem number 1627 - Graph Connectivity With Threshold

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by af-orozcog** [comment]
Can you please assign this to me? Thank you

**Comment by verma-pulkit** [comment]
I would like to contribute in the cpp code. please assign this to me.
