### ISSUE TITLE
198 |  HouseRobber.cpp | C++

### ISSUE THREAD

**Issue by Piyush228** [SHY-Corp/LeetCode-Solutions#799]
## HouseRobber

**What will change** -
Providing optimum solution to the problem in C++ language

### Type of Issue -

the code does not accept all test cases

- [x] Adding New Code
- [x] Improving Code
- [x] Improving Documentation
- [x] Bug Fix

### Programming Language

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by Piyush228** [comment]
Please assign this to me

**Comment by verma-pulkit** [comment]
I would like to contribute in the cpp code. please assign this to me.

**Comment by SSKale1** [comment]
This problem already exists in the codebase.
