### ISSUE TITLE
2 | Add Two Numbers | Python

### ISSUE THREAD

**Issue by SSKale1** [SHY-Corp/LeetCode-Solutions#8]
## **`Title`** - 2. Add Two Numbers

**What will change** - Add Solution

### Type of Issue -
- [x] Adding New Code

### Programming Language

- [x] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/Ftbj4a

Happy Coding,

**Comment by VIPUL662** [comment]
yes i want to do it.

**Comment by SSKale1** [comment]
- [x] Assigning to @VIPUL662 .
Make sure you read and follow the contribution guidelines. And submit according to the Leetcode Solution with proper Comments explaining the program and Time/Space Complexities if Applicable.

**Comment by VIPUL662** [comment]
[add two no. in phython.py.txt](https://github.com/SHY-Corp/LeetCode-Solutions/files/5329454/add.two.no.in.phython.py.txt)

**Comment by SSKale1** [comment]
@VIPUL662 you need to Make a PR and reference this issue number for it to get merged.

**Comment by chehak123** [comment]
Please assign to me also

**Comment by SSKale1** [comment]
@chehak123 we're assigning 1 issue per person. You can create any other issue you would like.
