### ISSUE TITLE
7 |  Reverse_Integer.cpp | C++

### ISSUE THREAD

**Issue by Piyush228** [SHY-Corp/LeetCode-Solutions#801]
## Reverse Integer
**What will change** -
Providing optimum solution to the problem in C++ language

### Type of Issue -

Adding New Code and Bug Fix

- [x] Adding New Code
- [x] Improving Code
- [x] Improving Documentation
- [x] Bug Fix

### Programming Language
C++

- [x] Python
- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by Piyush228** [comment]
Please assign this to me

**Comment by verma-pulkit** [comment]
I would like to contribute in this for cpp. Please assign.

**Comment by SSKale1** [comment]
@Piyush228 This problem already exists in the codebase.
