### ISSUE TITLE
8 | String to Integer (atoi) | C++

### ISSUE THREAD

**Issue by drewmich** [SHY-Corp/LeetCode-Solutions#806]
## **`String to Integer (atoi)`** -

**What will change** -

Will add code for an efficient solution to this problem

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by drewmich** [comment]
Can I be assigned this issue please?

**Comment by zjzh** [comment]
Hello, @drewmich,  I see you assign issue  label, why could you assign issue label?  Is it the person who is the member of the repository or is granted the permission can label it?
