### ISSUE TITLE
1510 | Stone Game IV | Java

### ISSUE THREAD

**Issue by IshaanSinghal1** [SHY-Corp/LeetCode-Solutions#81]
## **`Title`** - 1510 | STONE GAME IV

**What will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [] Improving Code
- [] Improving Documentation
- [] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [] Python
- [] C++
- [x] Java
- [] SQL

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by IshaanSinghal1** [comment]
Assign this to me.

**Comment by Yashica7** [comment]
- [x] Assigned you for this @IshaanSinghal1
