### ISSUE TITLE
28 | Implement strStr() | C++

### ISSUE THREAD

**Issue by drewmich** [SHY-Corp/LeetCode-Solutions#810]
## **`Implement strStr()`** -

**What will change** -

Will add code for a clean solution to this problem

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [] Improving Code
- [] Improving Documentation
- [] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [] Python
- [x] C++
- [] Java
- [] SQL

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by drewmich** [comment]
Could I please be assigned this issue?

**Comment by pawki07** [comment]
I would like to work on this issue by using python. Please assign it to me.
