### ISSUE TITLE
617 | Merge Two Binary Trees | C++

### ISSUE THREAD

**Issue by nyctophiliacme** [SHY-Corp/LeetCode-Solutions#819]
## **`Merge Two Binary Trees`** -

**What will change** - Adding C++ solution to Merge Two Binary Trees

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by nyctophiliacme** [comment]
Hi, Please assign this issue to me.

**Comment by sbindal057** [comment]
hey, I am interested. Please assign this to me.
