### ISSUE TITLE
1356 | Sort Integers by The Number of 1 Bits | Python

### ISSUE THREAD

**Issue by wpedrak** [SHY-Corp/LeetCode-Solutions#82]
## **`Title`** - 1356. Sort Integers by The Number of 1 Bits

**What will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [x] Python
- [ ] C++
- [ ] Java
- [ ] SQL

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by wpedrak** [comment]
Please assign me

**Comment by SSKale1** [comment]
@wpedrak let's cool down for a while let others contribute to some issue.

**Comment by Bhavya-Tripathi** [comment]
I would like to contribute a solution in python. Please assign it to me

**Comment by hjpassion** [comment]
please assign some tasks with me i want to contribute in this event

**Comment by SSKale1** [comment]
- [x] Assigning to @Bhavya-Tripathi

**Comment by OMEGAeNcore** [comment]
I can use java for this. Please assign me this.
