### ISSUE TITLE
654 | Maximum Binary Tree | C++

### ISSUE THREAD

**Issue by nyctophiliacme** [SHY-Corp/LeetCode-Solutions#820]
## **`Maximum Binary Tree`** -

**What will change** - Adding C++ solution to Maximum Binary Tree

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by nyctophiliacme** [comment]
Hi, Please assign this issue to me.

**Comment by prinsusinghal** [comment]
Hi @nyctophiliacme , I want to work on this issue. Assign it to me.
