### ISSUE TITLE
15 | 3Sum | Python

### ISSUE THREAD

**Issue by noksenberg** [SHY-Corp/LeetCode-Solutions#821]
## **Add 3Sum Solution in Python** 

**What will change** -
Add 3Sum Solution in Python.

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [x] Python
- [ ] C++
- [ ] Java
- [ ] SQL

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by noksenberg** [comment]
Please assign this issue to me :)

**Comment by Arushi04** [comment]
I would love to work on it!

**Comment by Ashutoshnegi880** [comment]
I would like to code it in c++

**Comment by 96RadhikaJadhav** [comment]
Could you please assign this issue to me?

**Comment by Psion05** [comment]
I would like to work on this issue, please assign it to me :)
