### ISSUE TITLE
124 |  Binary Tree Maximum Path Sum | Java

### ISSUE THREAD

**Issue by abhi2694** [SHY-Corp/LeetCode-Solutions#83]
## **` Binary Tree Maximum Path Sum`** -

**What will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [ ] Python
- [ ] C++
- [x] Java
- [ ] SQL

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by abhi2694** [comment]
@SSKale1 I would like to take this up.

**Comment by AryashDubey** [comment]
Please Assign Me!

**Comment by SSKale1** [comment]
- [x] Assigning to @abhi2694 for issue creation.

**Comment by hjpassion** [comment]
if there is any part left in this project i would love to contribute please assign if its possible
