### ISSUE TITLE
231 | Power of Two | C++

### ISSUE THREAD

**Issue by keshavga1209** [SHY-Corp/LeetCode-Solutions#834]
## **`Title`** - 231. Power of Two

**What will change** - Adding C++ code for 231. Power of Two of Leetcode

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [ ] Python
- [x] C++
- [ ] Java
- [ ] SQL

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by pawki07** [comment]
Please assign this issue to me.

**Comment by Skillz619** [comment]
can I work on this
