### ISSUE TITLE
1528 | Shuffle String | C++

### ISSUE THREAD

**Issue by Piyush228** [SHY-Corp/LeetCode-Solutions#839]
## Shuffle String

**What will change** -
this question is not present in C++ folder

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by t3bol90** [comment]
Can you assign it for me as hacktoberfest contribution :3 @Piyush228

**Comment by Piyush228** [comment]
@t3bol90 their are many question in leetcode ,find it which is not present in leetcodeSolution and create an issue then you will definately get assign of new issue you created
if you want new problem then say yes
Happy Coding
