### ISSUE TITLE
138 | Copy List with Random Pointer | Python3

### ISSUE THREAD

**Issue by SaxenaKartik** [SHY-Corp/LeetCode-Solutions#850]
## **`Title`** - Copy List with Random Pointer

**What will change** - Add new solution in Python3

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] Python

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by SaxenaKartik** [comment]
Awaiting assignment for the same

**Comment by 96RadhikaJadhav** [comment]
Could you please assign this issue to me?
