### ISSUE TITLE
1480 | Running Sum of 1d Array | Java

### ISSUE THREAD

**Issue by AlexandreVelloso** [SHY-Corp/LeetCode-Solutions#864]
## **Running Sum of 1d Array**

**What will change**
Create a solution in Java for this problem

### Type of Issue

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Java

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by AlexandreVelloso** [comment]
Assign that to me please

**Comment by 91078781** [comment]
May I be assigned this issue please?
