### ISSUE TITLE
181 | Employees Earning More Than Their Managers | SQL

### ISSUE THREAD

**Issue by ChakPC** [SHY-Corp/LeetCode-Solutions#87]
## **`Title`** -

**What will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [ ] Python
- [ ] C++
- [ ] Java
- [x] SQL

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by ChakPC** [comment]
I am really eager to submit my solution to this problem...Please allow me to generate a pull request regarding this

**Comment by SSKale1** [comment]
- [x] Assigning to @ChakPC
