### ISSUE TITLE
606 | Construct String from Binary Tree | C++

### ISSUE THREAD

**Issue by srajantiwari** [SHY-Corp/LeetCode-Solutions#871]
## **`Title`** - Construct String from Binary Tree

**What will change** - I will add the solution for the above problem in C++ with comments for better understanding.

### Type of Issue - 

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by h20190907** [comment]
@srajantiwari I would like to work on this. Please assign this to me

**Comment by amitShindeGit** [comment]
I would like to work on it,please assign it to me.

**Comment by verma-pulkit** [comment]
I would like to contribute in cpp.
