### ISSUE TITLE
49 | Group Anagrams | C++

### ISSUE THREAD

**Issue by h20190907** [SHY-Corp/LeetCode-Solutions#874]
## **`Group Anagrams`** -

**What will change** -

### Type of Issue -
- [x] Adding New Code

### Programming Language
- [x] C++

### Self Check 

- Ask for an issue assignment and wait to get assigned to it before making Pull Request.
- Add your file to the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by h20190907** [comment]
Please assign this issue to me. I will follow proper guidelines and provide an optimized solution

**Comment by shubhamsolank24** [comment]
i can do it you can assign this to me.
