### ISSUE TITLE
1095 | Find in Mountain Array  | C++

### ISSUE THREAD

**Issue by h20190907** [SHY-Corp/LeetCode-Solutions#875]
## **`Find in Mountain Array`** -

**Add C++ solution to the problem** -

### Type of Issue -
- [x] Adding New Code

### Programming Language
- [x] C++

### Self Check 

- Ask for an issue assignment and wait to get assigned to it before making Pull Request.
- Add your file to the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by h20190907** [comment]
Please assign this issue to me. I will provide the optimized and well documented solution

**Comment by vijaykumarsunkari** [comment]
I wanted to add a game. Am i allowed to do that. I have written that game on my own.

**Comment by SSKale1** [comment]
@vijaykumarsunkari This repo is only for the Solutions of Leetcode Problems.
