### ISSUE TITLE
875 | Koko Eating Bananas | C++

### ISSUE THREAD

**Issue by h20190907** [SHY-Corp/LeetCode-Solutions#876]
## **`Koko Eating Bananas`** -

**What will change** - 
Add C++ solution to the problem

### Type of Issue -
- [x] Adding New Code

### Programming Language
- [x] C++

### Self Check 

- Ask for an issue assignment and wait to get assigned to it before making Pull Request.
- Add your file to the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by h20190907** [comment]
Please assign this issue to me.

**Comment by jaydeshmukh007** [comment]
Please assign this issue to me.

**Comment by SaiShashank12** [comment]
Please assign this issue to me.

**Comment by hemant2705** [comment]
Please assign issue to me

**Comment by AbhJ** [comment]
Please assign to me I am a third year undergraduate in Electrical Engineering IIT Kharagpur with good background in competitive programming

**Comment by h20190907** [comment]
@swaingotnochill Could you please look into my pull request, and merge it into the respository, if everything looks fine
