### ISSUE TITLE
1011 | Capacity To Ship Packages Within D Days | C++

### ISSUE THREAD

**Issue by h20190907** [SHY-Corp/LeetCode-Solutions#877]
## **`Capacity To Ship Packages Within D Days`** -

**Add a C++ solution to the leetcode problem** -

### Type of Issue -
- [x] Adding New Code

### Programming Language
- [x] C++

### Self Check 

- Ask for an issue assignment and wait to get assigned to it before making Pull Request.
- Add your file to the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by h20190907** [comment]
Please assign this issue to me.

**Comment by jaydeshmukh007** [comment]
please assign this issue to me i will get the most efficient solution.

**Comment by jaydeshmukh007** [comment]
I have already solved this problem

**Comment by jaydeshmukh007** [comment]
I have already solved this problem

**Comment by h20190907** [comment]
I have also solved this problem, which is why I raised to issue to contribute to the solution. Please assign the issue to me.

**Comment by prasath1105** [comment]
Can you please assign this issue to me already solved this problem.

**Comment by singlatushar07** [comment]
Assign an issue to me

**Comment by h20190907** [comment]
@swaingotnochill @SSKale1 I have solved the problem, and added the solution following proper contributing guidelines. Could you please have a look and close the PR if everything looks fine. This is for the Hacktoberfest. Thanks in advance!

**Comment by h20190907** [comment]
i closed the issue by mistake, reopening it.
