### ISSUE TITLE
1283 | Find the Smallest Divisor Given a Threshold | C++

### ISSUE THREAD

**Issue by h20190907** [SHY-Corp/LeetCode-Solutions#878]
## **`Find the Smallest Divisor Given a Threshold`** -

**Add optimized C++ solution in the C++ folder for the problem** -

### Type of Issue -

- [x] Adding New Code

### Programming Language
- [x] C++

### Self Check 

- Ask for an issue assignment and wait to get assigned to it before making Pull Request.
- Add your file to the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by h20190907** [comment]
Please assign this issue to me. I will provide an optimized solution to this problem

**Comment by singhalharsh9** [comment]
please assign this issue to me.

**Comment by mr-abhi-k** [comment]
can u please assign me this issue to me?

**Comment by h20190907** [comment]
@swaingotnochill I have created the PR for this issue, Could you please look into it and close it if everything looks fine?
