### ISSUE TITLE
44 | Wildcard Matching | Python

### ISSUE THREAD

**Issue by vijay5158** [SHY-Corp/LeetCode-Solutions#88]
## **`Title`** -

**What will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [x] Python
- [ ] C++
- [ ] Java
- [ ] SQL

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by vijay5158** [comment]
Please assign this to me

**Comment by Yashica7** [comment]
- [x] Assigned @vijay5158
