### ISSUE TITLE
735 | Asteroid Collision | C++   

### ISSUE THREAD

**Issue by Piyush228** [SHY-Corp/LeetCode-Solutions#881]
## Asteroid Collision 

**What will change** -
Add new leetcode problem in the C++ folder with optimized C++ solution

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by Piyush228** [comment]
please assign to me

**Comment by jaydeshmukh007** [comment]
Please assign this issue to me.

**Comment by tyagi619** [comment]
Can I solve this issue if its still open and unassigned?

**Comment by tyagi619** [comment]
I have solved this problem. Can I make a pull request?
