### ISSUE TITLE
2 | Add Two Numbers | Python

### ISSUE THREAD

**Issue by DCCollao** [SHY-Corp/LeetCode-Solutions#89]
## **`Fixing Add Two Numbers solution`** -

**What will change** -
Current solution does not really solve the problem. I will add my own solution.
### Type of Issue -

- [x] Adding New Code
- [x] Improving Code
- [x] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

**Comment by DCCollao** [comment]
Please assign to me

**Comment by MaChimal** [comment]
I just need to improve and document the solution you already gave?

**Comment by DCCollao** [comment]
The current solution does not solve the problem listed in LeetCode. I'm asking the repo owner to allow me to make a PR fixing this problem.

**Comment by SSKale1** [comment]
- [x] Assigned to @DCCollao
