### ISSUE TITLE
7 | Reverse_Integer | C++

### ISSUE THREAD

**Issue by ravjotkaamra** [SHY-Corp/LeetCode-Solutions#894]
## **`Title`** - Reverse Integer

**What will change** - The code is in the wrong directory, it is a Java code and should be in Java Directory.
Also the name of the file should be Reverse_Integer.java

### Type of Issue - 

Please add/delete options that are not relevant.

- [x] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [x] C++
- [x] Java

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by ravjotkaamra** [comment]
Could you assign this to me, please?

**Comment by potter1024** [comment]
Please assign it to me

**Comment by verma-pulkit** [comment]
I would like to contribute in cpp.
