### ISSUE TITLE
INVALID |  | C++

### ISSUE THREAD

**Issue by potter1024** [SHY-Corp/LeetCode-Solutions#896]
## **`Longest Increasing Path in a Matrix `** -

**What will change** - Code to be added

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by potter1024** [comment]
Please assign it to me.

**Comment by verma-pulkit** [comment]
I would like to contribute in cpp.
