### ISSUE TITLE
1315 | Sum of Nodes with Even-Valued Grandparent | Java

### ISSUE THREAD

**Issue by patelviralb** [SHY-Corp/LeetCode-Solutions#90]
## **`Title`** - [**`1315. Sum of Nodes with Even-Valued Grandparent`**](https://leetcode.com/problems/sum-of-nodes-with-even-valued-grandparent/)

**What will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Java

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by patelviralb** [comment]
Please assign to me

**Comment by Yashica7** [comment]
- [x] Assigned @patelviralb
