### ISSUE TITLE
647 | Palindromic Substrings | Java

### ISSUE THREAD

**Issue by patelviralb** [SHY-Corp/LeetCode-Solutions#91]
## **`Title`** - [**`647. Palindromic Substrings`**](https://leetcode.com/problems/palindromic-substrings/)

**What will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Java

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by patelviralb** [comment]
Please assign to me

**Comment by Yashica7** [comment]
- [x] Assigned @patelviralb

**Comment by SusnatoPrime007** [comment]
Please also assign me to this.
