### ISSUE TITLE
77 | Combinations | C++

### ISSUE THREAD

**Issue by harshbhagwani94** [SHY-Corp/LeetCode-Solutions#920]
## **`Title`** - 77 | Combinations

**What will change** - C++ code for problem 77 Combinations will be added.

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by harshbhagwani94** [comment]
@swaingotnochill Can you assign this issue to me?

**Comment by verma-pulkit** [comment]
I would like to work on this in cpp.

**Comment by AmeyaPhadnis-2019H1030012G** [comment]
Please assign this issue to me. I am new to the open-source community and looking forward to opportunities to contribute. Thanks in advance!
