### ISSUE TITLE
84 | Largest Rectangle in Histogram | Java

### ISSUE THREAD

**Issue by abhishtjoshi** [SHY-Corp/LeetCode-Solutions#927]
## **`Title`** - Largest Rectangle in Histogram

**What will change** - Adding new code to the problem no. 84 of leetcode in java language

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] Java

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by abhishtjoshi** [comment]
@SSKale1 @swaingotnochill pls assign this task to me

**Comment by snehaa1989** [comment]
@SSKale1 can i do it in c++? if so, please assign this to me

**Comment by elizabethqiu** [comment]
Can I contribute to this in Java? Thank you :)
