### ISSUE TITLE
141. | Linked List Cycle | C++

### ISSUE THREAD

**Issue by vishalghosh7** [SHY-Corp/LeetCode-Solutions#929]
## **`Title`** - Finding a cycle in a Linked List

**What will change** -  Add a C++ solution to the above mentioned problem

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by vishalghosh7** [comment]
Would you please assign me the given problem?

**Comment by verma-pulkit** [comment]
I would like to contribute in cpp.

**Comment by snehaa1989** [comment]
please assign this to me

**Comment by AmeyaPhadnis-2019H1030012G** [comment]
Please assign this issue to me. I am new to the open-source community and looking forward to opportunities to contribute. Thanks in advance!
