### ISSUE TITLE
invalid

### ISSUE THREAD

**Issue by patelviralb** [SHY-Corp/LeetCode-Solutions#93]
## **`Title`** - [**`3. Longest Substring Without Repeating Characters`**](https://leetcode.com/problems/longest-substring-without-repeating-characters/)

**What will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Java

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by patelviralb** [comment]
Please assign to me

**Comment by shevya06** [comment]
I would like to do this

**Comment by rsrahul1000** [comment]
Hi @Yashica7 , would you please assign this to me? I've already started solving this problem..

**Comment by SSKale1** [comment]
@patelviralb we'll be assigning this to @shevya06 you cool off for a bit.

**Comment by shuai-yang** [comment]
would you please assign this to me?

**Comment by SSKale1** [comment]
@shevya06 you plan on implementing it?

**Comment by shevya06** [comment]
I'm sorry was facing some issue with this one , you can assign it to someone else if that's possible

**Comment by SSKale1** [comment]
Okay no Problem.

**Comment by SSKale1** [comment]
@shuai-yang You still wanna do this?
