### ISSUE TITLE
54. ||Spiral Matrix || CPP

### ISSUE THREAD

**Issue by verma-pulkit** [SHY-Corp/LeetCode-Solutions#936]
## **`Title`** -

New code for 54. Spiral Matrix
New code

Please add/delete options that are not relevant.

- [x] Adding New Code
- [] Improving Code
- [] Improving Documentation
- [] Bug Fix

### Programming Language
Please add/delete options that are not relevant.

- [] Python
- [x] C++
- [] Java
- [] SQL

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by snehaa1989** [comment]
assign this to me please

**Comment by SSKale1** [comment]
This problem already exists in the codebase.
