### ISSUE TITLE
949 | Largest Time for Given Digits | C++

### ISSUE THREAD

**Issue by Darsh4521** [SHY-Corp/LeetCode-Solutions#938]
## **`Largest Time for Given Digits`** -

**What will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [] Improving Code
- [] Improving Documentation
- [] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [] Python
- [x] C++
- [] Java
- [] SQL

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by Darsh4521** [comment]
Assign this to me please.

**Comment by AmeyaPhadnis-2019H1030012G** [comment]
Please assign this issue to me. I am new to the open-source community and looking forward to opportunities to contribute. Thanks in advance!

**Comment by Darsh4521** [comment]
i am also new to the open source community and looking to contribute as well. So plz assign this one to me
