### ISSUE TITLE
1329 || Sort the Matrix Diagonally || CPP

### ISSUE THREAD

**Issue by verma-pulkit** [SHY-Corp/LeetCode-Solutions#939]
## **`Title`** -1329. Sort the Matrix Diagonally

**What will change** -
New code for 1329. Sort the Matrix Diagonally

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [] Improving Code
- [] Improving Documentation
- [] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [] Python
- [x] C++
- [] Java
- [] SQL

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by drishtipeshwani** [comment]
can this issue be assigned to me ?

**Comment by heidar55** [comment]
Would you please assign me this project to work on it?
