### ISSUE TITLE
7 | Reverse Integer | Python

### ISSUE THREAD

**Issue by Ares358** [SHY-Corp/LeetCode-Solutions#94]
## **`7 | Reverse Integer | Python`** -

**What will change** -

Add Python solution to the LeetCode problem: 7. Reverse Integer

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] Python

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by Ares358** [comment]
Can I be assigned this?
Thnx!

**Comment by AjayArvind2207** [comment]
I would love to be assigned this!
Thanks in advance :)

**Comment by SSKale1** [comment]
- [x] Assigned to @Ares358 for issue creation.

**Comment by SSKale1** [comment]
@AjayArvind2207 you can create any another issue and ask to be assigned to it.
