### ISSUE TITLE
917 | Reverse Only Letters | C++

### ISSUE THREAD

**Issue by pavalucas** [SHY-Corp/LeetCode-Solutions#941]
## **`Reverse Only Letters`** -

**What will change** -  Add C++ solution to the problem

### Type of Issue -  Adding New Code

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by pavalucas** [comment]
Please assign it to me.

**Comment by namrata18s** [comment]
please assign to me @pavalucas
