### ISSUE TITLE
34 | Find First and Last Position of Element in Sorted Array | C++

### ISSUE THREAD

**Issue by drewmich** [SHY-Corp/LeetCode-Solutions#946]
## **`34 | Find First and Last Position of Element in Sorted Array | C++`** -

**What will change** -

Will add code for optimal solution to "34. Find First and Last Position of Element in Sorted Array"

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by drewmich** [comment]
Can I please be assigned this issue?

**Comment by Nitish-web-nik** [comment]
I want to contribute in this issue, Please assign.

**Comment by Erixx123** [comment]
Can you assign me?

**Comment by ARsh-ALgo** [comment]
Happy to contribute here.
