### ISSUE TITLE
204 | Count Primes  | Python

### ISSUE THREAD

**Issue by fawwaz** [SHY-Corp/LeetCode-Solutions#948]
## **`204. Count Primes`** -

**What will change** -
Add New Code for Count Primes

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by fawwaz** [comment]
Cna you assign it to me ?

**Comment by Erixx123** [comment]
Could you assign me?
