### ISSUE TITLE
87 | Scramble String | C++

### ISSUE THREAD

**Issue by ricky1812** [SHY-Corp/LeetCode-Solutions#95]
## **`Title`** -

**What will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Code
- [x] Improving Documentation
- [x] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [ ] Python
- [x] C++
- [ ] Java
- [ ] SQL

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by ricky1812** [comment]
I want to work on this issue.

**Comment by Rohit-varma** [comment]
I want to work on this issue @ricky1812 can you please assign me?

**Comment by Yashica7** [comment]
- [x] Assigned @ricky1812
