### ISSUE TITLE
50 | Pow(x, n) | Java

### ISSUE THREAD

**Issue by andresq** [SHY-Corp/LeetCode-Solutions#96]
## **`50. Pow(x, n) | Java`** -

**What will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Java

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by andresq** [comment]
I will work on this

**Comment by Yashica7** [comment]
- [x] Assigned @andresq

**Comment by shevya06** [comment]
I would like to work on this
