### ISSUE TITLE
1 | Two Sum| PHP

### ISSUE THREAD

**Issue by cbanupama** [SHY-Corp/LeetCode-Solutions#962]
## **`Add PHP solution for two sum problem`** -

**What will change** -

### Improvement - 

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Php

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by cbanupama** [comment]
Please assign the issue to me.

**Comment by beertocode** [comment]
Please assign me this issue.

**Comment by pstreemaze** [comment]
Please assign me this issue. Can code it in cpp/Java

**Comment by SSKale1** [comment]
We don't have a folder for PHP at this stage.
