### ISSUE TITLE
82 | Remove Duplicates from Sorted List II | C++

### ISSUE THREAD

**Issue by anand-2020** [SHY-Corp/LeetCode-Solutions#965]
## **`Remove Duplicates from Sorted List II`** -

**Add C++ solution to the problem** -

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by anand-2020** [comment]
Please assign this issue to me. I will provide a optimized and well structured solution

**Comment by KarthiK2601** [comment]
Can you assign me this ?

**Comment by mr-abhi-k** [comment]
can u pls assign me this issue, i am new to open source and wanna start my contribution with works which i love....

**Comment by JOKUE2002** [comment]
@KarthiK2601 @mr-abhi-k anand-2020 asked first so he has the right of way. You may want to create more issues and we'll assign you to them.
