### ISSUE TITLE
938 | Range Sum of BST | C++

### ISSUE THREAD

**Issue by ravjotkaamra** [SHY-Corp/LeetCode-Solutions#968]
## **`Title`** -  Add new code for Range Sum of BST

**What will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by ravjotkaamra** [comment]
Could you assign this to me, please?

**Comment by JOKUE2002** [comment]
Of course. Have fun 😄
