### ISSUE TITLE
8 | Palindrome checker for strings | Python

### ISSUE THREAD

**Issue by PravunathSingh** [SHY-Corp/LeetCode-Solutions#97]
## **`Title`** -

**We will check if a given string is a palindrome or not** 

### Type of Issue   ##-

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x]  #Python

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by jessicasalbert** [comment]
I can work on this if you don't mind assigning it to me. Thanks!

**Comment by PravunathSingh** [comment]
Hey, @SSKale1 I have created this issue and I would like to work on it. Thanks!

**Comment by SSKale1** [comment]
- [x] Assigning to @PravunathSingh for issue creation.

**Comment by SSKale1** [comment]
@jessicasalbert you can create another issue and ask to be assigned to it. There are a lot of problems available anyway.
