### ISSUE TITLE
855 | Exam Room | C++

### ISSUE THREAD

**Issue by AnandPr123** [SHY-Corp/LeetCode-Solutions#977]
## **`Title`** - Exam Room

**What will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- Adding New Code

### Programming Language

Please add/delete options that are not relevant.

-  C++

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by drishtipeshwani** [comment]
Please assign this to me

**Comment by prasath1105** [comment]
can you please assign this issue already solves this problem

**Comment by Starkultra** [comment]
can you please assign this issue to me
