### ISSUE TITLE
107 | Binary Tree Level Order Traversal II | C++

### ISSUE THREAD

**Issue by harshbhagwani94** [SHY-Corp/LeetCode-Solutions#980]
## **`Title`** - Binary Tree Level Order Traversal II

**What will change** - New file will be added

### Type of Issue - Solution doesn't exist

Please add/delete options that are not relevant.

- [x] Adding New Code
- [] Improving Code
- [] Improving Documentation
- [] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [] Python
- [x] C++
- [] Java
- [] SQL

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by harshbhagwani94** [comment]
@SSKale1 Can you assign this issue to me?

**Comment by prasath1105** [comment]
Hi @harshbhagwani94 
Can you assign this issue to me I already solved this problem

**Comment by vivaswat19** [comment]
Can you assign this issue to me.

**Comment by JOKUE2002** [comment]
Here you go @harshbhagwani94 

@vivaswat19 you may open more issues to contribute to this repository

**Comment by SSKale1** [comment]
@harshbhagwani94 Why was this closed?

**Comment by harshbhagwani94** [comment]
@SSKale1 I have made pull request associated with this issue. Can you please validate it and merge with the main branch?

**Comment by SSKale1** [comment]
@harshbhagwani94 yes we'll be doing that. But we close the issue only when the PR has been merged.

**Comment by harshbhagwani94** [comment]
@SSKale1 thanks, I didn't know that. I saw people closing the issue without merging, that's why I closed. Sorry for that!

**Comment by SSKale1** [comment]
@harshbhagwani94 we may have to do it like that sometimes when the PR's are not being linked to the issue.
