### ISSUE TITLE
455 | Assign Cookies | python

### ISSUE THREAD

**Issue by vivaswat19** [SHY-Corp/LeetCode-Solutions#987]
Assign Cookies

**What will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by vivaswat19** [comment]
can you assign this issue to me.

**Comment by sawyer1997** [comment]
@swaingotnochill Can you please review my PR?

**Comment by vivaswat19** [comment]
@swaingotnochill please review my PR.
Thank you.
