### ISSUE TITLE
16 | 3Sum Closest | Python

### ISSUE THREAD

**Issue by carolinejoseph** [SHY-Corp/LeetCode-Solutions#992]
## **`Title`** - 16 | 3Sum Closest | Python

**What will change** - Add a solution for #16 3Sum Closest in Python
Given an array 'nums' of n integers and an integer 'target', find three integers in nums such that the sum is closest to target. Return the sum of the three integers. Assume that each input would have exactly one solution.

Example:
Input: nums = [-1,2,1,-4], target = 1
Output: 2 
Explanation: (-1 + 2 + 1 = 2)

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by carolinejoseph** [comment]
Please assign this problem to me

**Comment by sawyer1997** [comment]
@carolinejoseph Can you please add the problem statement, would be helpful.
