### ISSUE TITLE
20 | Valid Parentheses | Python

### ISSUE THREAD

**Issue by kajal-puri** [SHY-Corp/LeetCode-Solutions#996]
## **`Title`** - Valid Parentheses

**What will change** - Adding new code to the Problem 20 of leetcode in Python.

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

### Self Check 

- Ask for issue assignment and wait to get assigned to it before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/CXksGdn

Happy Coding,

**Comment by kajal-puri** [comment]
@SSKale1 @swaingotnochill Can you please assign this task to me? Thanks!

**Comment by AmeyaPhadnis-2019H1030012G** [comment]
Can I work on this,  I am new to the open-source community and looking forward to opportunities to contribute. Thanks in advance!
